' Gambas module file

Property Read TempFile As String
Property Read TempFileUrl As String
Property Read Source As String
Property Read TempFileRelative As String

Private $sourceText As String
Private $workinPathAbsolute As New NagatoWorkingFile
Private $workinPathRelative As New NagatoWorkingFileRelative

Public Sub ToHtmlDirect(argSourceText As String)

    $sourceText = argSourceText
    $workinPathAbsolute.Set(argSourceText)

End

Private Function TempFile_Read() As String

    Return $workinPathAbsolute.WorkingPath

End

Private Function TempFileUrl_Read() As String

    Return $workinPathAbsolute.WorkingUrl

End

Private Function Source_Read() As String

    Return $sourceText

End

Private Function TempFileRelative_Read() As String

    $workinPathRelative.Set($sourceText)

    Return $workinPathRelative.WorkingPath

End
