' Gambas module file

Private $tempPath As String

Private Function getHeader() As String
    
    Dim yukiHttpEquiv As String = Quote$("Content-Type")
    Dim yukiContent As String = Quote$("text/html; charset=UTF-8")
    Dim yukiHeader As String = "<head><meta http-equiv=&1 content=&2></head>"
    
    Return Subst$(yukiHeader, yukiHttpEquiv, yukiContent)
    
End

Public Sub ToHtmlDirect(argSourceText As String, Optional argFormat As String = "markdown_github") As String

    Dim yukiTempPathSource As String = IIf($tempPath, $tempPath, Temp$())
    Dim yukiOutput As String

    File.Save(yukiTempPathSource, getHeader() & MikuruMacro.Set(argSourceText))

    Exec ["pandoc", "-f", argFormat, "-t", "html", yukiTempPathSource] To yukiOutput

    Return yukiOutput

End

Public Sub ToHtmlSmart(argSourceText As String, Optional argFormat As String = "markdown_github") As String

    Dim yukiTempPathSource As String = IIf($tempPath, $tempPath, Temp$())
    Dim yukiTempPathTarget As String = Temp$() & ".html"
    Dim yukiOutput As String

    Debug yukiTempPathTarget

    File.Save(yukiTempPathSource, getHeader() & MikuruMacro.Set(argSourceText))

    Exec ["pandoc", "-s", "-S", "--toc", yukiTempPathSource, "-o", yukiTempPathTarget] Wait

    Return File.Load(yukiTempPathTarget)

End