' Gambas module file

Private $timer As New Timer As "Timer"

Public Sub Activate()
    
    NagatoDBus.Register()
    
    NagatoSystemObserver.Refresh()
    
    $timer.Start()
    
End

Public Sub Deactivate()
    
    NagatoDBus.Unregster()
    
End

Public Sub Timer_Timer()
    
    With NagatoSystemObserver
        Debug .Activated
        Debug .CpuUsage
        Debug .MemoryUsage
        Debug .SwapUsage
        Debug .ProcessCount
    End With
    
End

