' Gambas module file

Private Function getCpuDataElements() As String[]
    
    Dim yukiLine As String
    
    Exec ["head", "-n", "1", "/proc/stat"] To yukiLine
    
    Return Split(yukiLine, " ", "", True)
    
End

Public Sub _call() As Integer
    
    Dim yukiElements As String[] = getCpuDataElements()
    Dim yukiResult As Integer
    Dim yukiCount As Integer
    
    For yukiCount = 1 To 8
        yukiResult += CInt(yukiElements[yukiCount])
    Next
    
    Return yukiResult
    
End

