' Gambas module file

Public Function PageToMiB(argData As String) As String
    
    If argData <> 0 Then
        Return Format$(CInt(argData) / 256, "#,##0.00MiB") '1page=4KiB(1/256MiB)
    Else
        Return "-"
    Endif
    
End

Public Function KiloByteToMiB(argData As String) As String
    
    If argData <> 0 Then
        Return Format$(CInt(argData) / (1024 ^ 2), "###,###,###,##0.00MiB") 'byte to MiB
    Else
        Return "-"
    Endif
    
Catch
    Return "?"
    
End

Public Function UsageToString(argCpuUsage As Float) As String
    
    If argCpuUsage = 0 Then
        Return "-"
    Else
        Return Format$(argCpuUsage, "##0.00%")
    Endif
    
End
