name: nagato-gif-viewer
package-name: nagato-gif-viewer
id: io.github.takedanemuru.nagato-gif-viewer
version: 42.11.4
check-unique: false
short-description: gif viewer
long-description: |
    a simple gif viewer for NagatoBox
    this software is lisenced under S.O.S.License
authors: |
    copyright (c) 2018 takeda.nemuru
web-site: |
    https://takedanemuru.github.io/
