name: nagato-font-book
package-name: nagato-font-book
id: io.github.takedanemuru.nagato-font-book
version: 42.12.2
check-unique: false
short-description: font viewer
long-description: |
    font viewer

authors: |
    copyright (c) 2018 takedanemuru
web-site: |
    https:takedanemuru.github.io
