' Gambas module file

Public Enum CurrentCours, OldCours, Unmaintained

Private Function getCours(argDate As Date) As Integer
    
    Dim yukiCours As Integer = (Month(argDate) - 1) Div 3
    
    Return yukiCours + Year(argDate) * 4
    
End

Public Sub GetMaintainStatus(argLastModefied As Date) As Integer
    
    Dim yukiCurrentCours As Integer = getCours(Now())
    Dim yukiModefiedCours As Integer = getCours(argLastModefied)
    
    If yukiCurrentCours = yukiModefiedCours Then Return Me.CurrentCours
    If yukiCurrentCours = yukiModefiedCours + 1 Then Return Me.OldCours
    
    Return Me.Unmaintained
    
End
