' Gambas module file

Public Sub _call()
    
    Dim yukiMarkdown As String 
    Dim yukiProject As NagatoProject
    
    For Each yukiProject In NagatoProjectList.All
        yukiMarkdown &= Subst("## &1 (v&2)\n\n", yukiProject.Title, yukiProject.Version)
        yukiMarkdown &= Subst("Description : &1\n", UnQuote(yukiProject.Description))
        yukiMarkdown &= Subst("Last Modefied : &1\n\n", Format(yukiProject.LastModified, "yyyy-mm-dd"))
    Next
    
    Clipboard.Copy(yukiMarkdown, "text/plain")
    
End
