' Gambas module file

Public Sub _call()
    
    Dim yukiMarkdown As String = "# Applications List\n\n"
    Dim yukiProject As NagatoProjectForGithub
    
    Debug NagatoProjectListForGithub.All.Count
    
    For Each yukiProject In NagatoProjectListForGithub.All
        yukiMarkdown &= Subst("## &1 (v&2)\n\n", yukiProject.TitleHeader, yukiProject.Version)
        yukiMarkdown &= Subst("Description : &1\n", UnQuote(yukiProject.Description))
        yukiMarkdown &= Subst("Last Modefied : &1\n\n", Format(yukiProject.LastModified, "yyyy-mm-dd"))
        If yukiProject.ScreenshotsCount > 0 Then yukiMarkdown &= yukiProject.GetScreenShot(0)
        yukiMarkdown &= yukiProject.Document
    Next
    
    Try Kill User.Home &/ "NagatoBox/readme_extra/applications_list.md"
    File.Save(User.Home &/ "NagatoBox/readme_extra/applications_list.md", yukiMarkdown)
    
End
