' Gambas module file

Private Const Header1 As String = "num\t|Name\t|Version\t|Description\n"
Private Const Header2 As String = "----:\t|----\t|----\t|----\n"
Private Const Template As String = "&1\t|&2\t|&3\t|&4\n"

Public Sub _call()
    
    Dim yukiMarkdown As String = Header1 & Header2
    Dim yukiProject As NagatoProject
    Dim yukiNumber As Integer
    Dim yukiDescription As String
    
    For Each yukiProject In NagatoProjectList.All
        Inc yukiNumber
        With yukiProject
            yukiDescription = IIf(UnQuote(.Description), UnQuote(.Description), "-")
            yukiMarkdown &= Subst(Template, yukiNumber, .Title, .Version, yukiDescription)
        End With
    Next
    
    Clipboard.Copy(yukiMarkdown, "text/plain")
    
End
