name: nagato-image-viewer
package-name: nagato-image-viewer
id: io.github.takedanemuru.nagato-image-viewer
version: 0.0.1
check-unique: false
short-description: image viewer
long-description: |
    image viewer

authors: |
    copyright (c) 2018 takedanemuru
web-site: |
    https://takedanemuru.github.io
