' Gambas module file

Property Read Pattern As String
Property Read Name As String
Property Read Cache As String
Property Read SubDomains As String[]
Property Read Arguments As Collection

Public Sub AddTile(argMapView As MapView)
    
    With Me
        Debug .Name
        Debug .Pattern
        Debug .Cache
        argMapView.Map.AddTile(.Name, .Pattern, .Arguments, .Cache).SubDomains = .SubDomains
    End With
    
End

Private Function Pattern_Read() As String

    Return "https://khms{s}.google.fr/kh/v={version}&src=app&x={x}&y={y}&z={z}&s=Galile"

End

Private Function Name_Read() As String

    Return "GoogleMap" 

End

Private Function SubDomains_Read() As String[]

    Return ["0", "1", "2"]

End

Private Function Cache_Read() As String

    Return "gm"

End

Private Function Arguments_Read() As Collection

    'Return ["version": "121"]
    Return ["version": "310"]

End
