' Gambas module file

Private Sub openForm()
    
    Select Case NagatoSettingsForm.Main
        Case NagatoSettingsForm.HPlayer
            HaruhiPlayer.Show() 
            Application.MainWindow = HaruhiPlayer
        Case NagatoSettingsForm.HPlayList
            HaruhiPlayList.Show()
            Application.MainWindow = HaruhiPlayList
        Case NagatoSettingsForm.HCoverArt
            HaruhiCovergloobus.Show() 
            Application.MainWindow = HaruhiCovergloobus
    End Select
    
    NagatoDBus.Register()
    
End

Public Sub Main()
    
    NagatoArguments.Parsing()
    
    If NagatoDBus.IsUnique() Then
        NagatoQueue.Activate()
        openForm()
        If NagatoArguments.Paths Then NagatoQueue(MikuruSignal.ListAddMusic, NagatoArguments.Paths)
    Else
        NagatoDBus.NotUniqueSequence()
    End If
    
End
