' Gambas module file

Private Sub activateMusicQueue()
    
    Dim yukiPaths As String[] = NagatoArguments.Paths
    
    If yukiPaths.Count > 0 Then
        NagatoQueue.Activate(yukiPaths)
        HaruhiPlayer.Show()
        NagatoQueue.Play()
        Return
    Endif
    
Finally
    NagatoQueue.Activate()
    HaruhiPlayer.Show() 
    
End

Public Sub Main()
    
    If NagatoDBus.IsUnique() Then
        NagatoArguments.Parsing()
        activateMusicQueue() 'and show HaruhiPlayer 
    Else
        'Message.Warning(("nagato-player-x has been activated"), ("OK"))
        NagatoDBus.Proxy.MoveToCurrentDesktop()
    End If
    
End
