name: nagato-terminal
package-name: nagato-terminal
id: box.nagato.terminal
version: 42.10.45
check-unique: true
short-description: a multi-grid terminal emulator.
long-description: |
    A multi-grid terminal emulator.
    This software is licensed under S.O.S. License.
authers: |
    copyright (c) 2017-2018 takeda.nemuru
web-site: |
    https://github.com/takedanemuru/NagatoBox
