name: APPNAME
package-name: APPNAME
id: id.of.application
version: 42.11.1
check-unique: true
short-description: SHORT_DESCRIPTION
long-description: |
    LONG_DESCRIPTION.
    LONG_DESCRIPTION.
    LONG_DESCRIPTION.
authers: |
    copyright (c) YEAR AUTHERNAME
web-site: |
    https://somewhere.foo.bar/baz
