' Gambas module file

Public Enum None = 0
Public Enum FileNone = 1000, FileSave = 1002, FileSaveAs = 1003
Public Enum FileNew = 1104, FileOpenPath = 1105, FileOpen = 1101
Public Enum ViewNone = 2000, ViewPreview = 2001
Public Enum PublishNone = 3000, PublishPdf = 3001, PublishHtml = 3002, PublishPlainText = 3003
Public Enum PublishSlidy = 3004
Public Enum AppNone = 4000, AppAbout = 4001, AppQuit = 4002
