' Gambas module file

Public Enum None = 0
Public Enum FileNone = 1000, FileSave = 1002, FileSaveAs = 1003
Public Enum FileNew = 1101, FileNewMarkdownGitHub = 1102, FileNewTextile = 1103, FileNewReStructuredText = 1104
Public Enum FileOpen = 1201, FileOpenPath = 1210
Public Enum ViewNone = 2000, ViewPreview = 2001
Public Enum PublishNone = 3000, PublishPdf = 3001, PublishHtml = 3002, PublishPlainText = 3003
Public Enum PublishSlidy = 3004
Public Enum AppNone = 4000, AppAbout = 4001, AppQuit = 4002
