' Gambas module file

Property Read List As String[]

Public Function Get(argName As String, Optional argSize As Integer = 16) As Picture
    
    Return Image.Load(Subst$("pictures/icons/&1.png", argName)).Stretch(argSize, argSize).Picture
    
End

Private Function List_Read() As String[]

    Dim yukiPath As String
    Dim yukiResult As New String[]
    
    For Each yukiPath In Dir("pictures/icons").Sort()
        yukiResult.Add(File.BaseName(yukiPath))
    Next

    Return yukiResult

End
