' Gambas module file

Private $args As New NagatoArguments

Public Sub Main()
    
    $args.Parse()
    
    If NagatoDBus.IsUnique() Then
        NagatoDBus.Register()
        HaruhiMain.OpenWithPath($args.StartupPath)
        HaruhiMain.InitializeRecentIconView()
    Else
        Try DBus["org.gambas.nagato.text"]["/org/nagato/text", "org.gambas.nagato.text.nagatointerface"].SetFilePath($args.StartupPath)
    End If
    
End
