' Gambas module file

Private $startUpPath As String = ""

Private Sub parsingApplicationArguments()
    
    Dim yukiPath As String
    Dim yukiOtherOptions As String[]
    
    Args.Begin(("Usage"))
        yukiPath = Args.Get("o", "open", ("Open a file"), ("Path to open"))
    yukiOtherOptions = Args.End()
    
    If yukiPath <> "" Then
        $startUpPath = yukiPath
    Else If yukiOtherOptions.Count <> 0 Then
        $startUpPath = yukiOtherOptions[0]
    End If

End

Public Sub Main()
    
    parsingApplicationArguments()
    
    If NagatoDBus.IsUnique() Then
        Debug "unique"
        NagatoDBus.Register()
        HaruhiMain.OpenWithPath($startUpPath)
        HaruhiMain.InitializeRecentIconView()
    Else
        Debug "non unique"
        Try DBus["org.gambas.nagato.text"]["/org/nagato/text", "org.gambas.nagato.text.nagatointerface"].SetFilePath($startUpPath)
    End If
    
End
