' Gambas module file

Property ThemeName As String

Private Const KeyGtkThemeName As String = "gtk-theme-name"

Private $confgGtk2 As New NagatoConfigFile(NagatoSettings.PathGtk2)
Private $confgGtk3 As New NagatoConfigFile(NagatoSettings.PathGtk3)

Private Function ThemeName_Read() As String

    If $confgGtk2[KeyGtkThemeName] <> $confgGtk3[KeyGtkThemeName] Then
        Return ""
    Else
        Return $confgGtk3[KeyGtkThemeName]
    Endif

End

Private Sub ThemeName_Write(Value As String)

    $confgGtk3[KeyGtkThemeName] = Value
    $confgGtk2[KeyGtkThemeName] = Value

End
