' Gambas module file

Property Read Names As String[]

Private Const $themesDirectory As String = "/usr/share/themes"

Private $themeNames As New String[]

Private Sub setThemeName(argPath As String)
    
    Dim yukiPath As String
    Dim yukiHasGtk2 As Boolean = False
    Dim yukiHasGtk3 As Boolean = False
    
    For Each yukiPath In Dir(argPath)
        If yukiPath = "gtk-2.0" Then yukiHasGtk2 = True
        If yukiPath = "gtk-3.0" Then yukiHasGtk3 = True
    Next
    
    If yukiHasGtk2 And If yukiHasGtk3 Then $themeNames.Add(File.Name(argPath))
    
End

Public Sub Reload()
    
    Dim yukiPath As String
    
    For Each yukiPath In Dir($themesDirectory)
        setThemeName($themesDirectory &/ yukiPath) 
    Next
    
End

Private Function Names_Read() As String[]

    Return $themeNames.Sort(gb.Ascent)

End
