' Gambas module file

Public Sub Get(argForecastText As String) As String
    
       Select Case argForecastText
        Case "clear"
            Return ("Clear")
        Case "sunny"
            Return ("Sunny")
        Case "mostlysunny"
            Return ("Mostly Sunny")
        Case "fog"
            Return ("Fog") 
        Case "hazy"
            Return ("Hazy")
        Case "rain"
            Return ("Rain")
        Case "chancerain"
            Return ("Chance of Rain")
        Case "snow"
            Return ("Snow")
        Case "sleet"
            Return ("Sleet")
        Case "flurries"
            Return ("Flurries")
        Case "chanceflurries"
            Return ("Chance of Flurries") 
        Case "chancesleet"
            Return ("Chance of Sleet")
        Case "chancesnow"
            Return ("Chance of Snow")
        Case "tstorms"
            Return ("Thunder Storms") 
        Case "chancetstorms"
            Return ("Chance of Thunder Storms")
        Case "cloudy"
            Return ("Cloudy")
        Case "partlycloudy"
            Return ("Partly Cloudy")
        Case "mostlycloudy"
            Return ("Mostly Cloudy")
        Default
            Return ("Unknown")
    End Select
 
    
End
