' Gambas module file

Public Function GetPath(argDir As String, argName As String) As String ' This function should return whole path.
    
    Dim yukiAlternativename As String
    Dim yukiCounter As Integer = 1
    
    If Not Exist(argDir &/ argName) Then Return argDir &/ argName
    
    Do
        yukiAlternativename = argDir &/ Subst$("&1(&2)", argName, yukiCounter)
        If Not Exist(yukiAlternativename) Then Return yukiAlternativename
        Inc yukiCounter 
    Loop
    
End
