' Gambas module file

Public Sub GetSecondToString(argSecond As Integer) As String
    
    Dim yukiResult As String = ""
    
    If argSecond >= 3600 Then yukiResult = Subst$("&1:", argSecond Div 3600)
    If argSecond >= 3600 Then
        yukiResult &= Format$((argSecond Mod 3600) Div 60, "0#:")
    Else
        yukiResult &= Subst$("&1:", (argSecond Mod 3600) Div 60)
    Endif
    yukiResult &= Format$(argSecond Mod 60, "0#")
    
    Return yukiResult
    
End
