.TH APPNAME 1 Month,YEAR
.SH NAME
APPNAME - SHORT_DESCRIPTION
.SH SYNOPSIS
.BR APPNAME 
[-h][-v]
.SH DESCRIPTION
SHORT_DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-v\fR
show version and exit
.SH LICENSE
APPNAME is licensed under S.O.S.License
.SH AUTHERS
AUTHERNAME <auther.name@address.com>
