' Gambas module file

Property Read Home As Integer
Property Read Back As Integer
Property Read Forward As Integer
Property Read Up As Integer
Property Read Reload As Integer 

Private $seriesHeader As Integer = MikuruSeriesHeader.Move


Private Function Home_Read() As Integer

    Return $seriesHeader + 1

End

Private Function Back_Read() As Integer

    Return $seriesHeader + 2

End

Private Function Forward_Read() As Integer

    Return $seriesHeader + 3

End

Private Function Up_Read() As Integer

    Return $seriesHeader + 4

End

Private Function Reload_Read() As Integer

    Return $seriesHeader + 5

End
