' Gambas module file

Private $timer As New Timer As "MainTimer"
Private $weatherCheckFlag As Boolean = False
Private $directoryObserver As NagatoDirectoryObserver

Private Sub initializeDirectoryObserverForDesktopDirectory()
    
    $directoryObserver = New NagatoDirectoryObserver As "DirectoryObserver"
    
    With $directoryObserver
        .Directory = MikuruPath.Desktop
        .IntervalSecond = 2
    End With
    
End

Public Sub Main()
    
    If Not NagatoDBus.IsUnique() Then Return
    
    Shell Subst$("nagato-taskmanager --register &1", Application.Name)
    
    NagatoUPower.EnsureActivation()
    
    NagatoIconOrder2.RefreshAll()
    NagatoIconOrder2.Sort()
    
    $timer.Enabled = True
    
    initializeDirectoryObserverForDesktopDirectory()
    
    NagatoDBus.Register()
    
End

Public Sub MainTimer_Timer()
    
    NagatoIconOrder2.Refresh("nagato-systemmonitor-key")
    
    If Minute(Now()) = 0 Or If Not NagatoWeatherCache.IsReady Then
        If $weatherCheckFlag And If NagatoWeatherCache.IsReady Then Return
        $weatherCheckFlag = True
        NagatoWeatherCache.Activate()
    Else
        $weatherCheckFlag = False
    Endif
    
End

Public Sub DirectoryObserver_Deleted(argFileName As String)
    
    NagatoIconOrder2.Delete(argFileName)
    
End

Public Sub DirectoryObserver_Modefied(argFileName As String)
    
    NagatoIconOrder2.Modefied(argFileName)
    
End
