' Gambas module file

Public Function GetDeviceIcon(argType As Integer) As Picture
    
    Select Case argType
        Case 1
            Return MikuruIcon.Get("plug")
        Case 2
            Return MikuruIcon.Get("battery")
        Default
            Return MikuruIcon.Get("question")
    End Select
    
End

Public Function GetDeviceType(argType As Integer) As String
    
    Select Case argType
        Case 0
            Return "Unknown"
        Case 1
            Return "Line power"
        Case 2
            Return "Battery"
        Case 3
            Return "UPS"
        Case 4
            Return "Monitor"
        Case 5
            Return "Mouse"
        Case 6
            Return "Keyboard"
        Case 7
            Return "PDA"
        Case 8
            Return "Phone"
        Default
            Return "uknown"
    End Select
    
End

Public Function GetDeviceState(argType As Integer) As String
    
    Select Case argType
        Case 0
            Return "Unknown"
        Case 1
            Return "Charging"
        Case 2
            Return "Discharging"
        Case 3
            Return "Empty"
        Case 4
            Return "Fully charged"
        Case 5
            Return "Pending charge"
        Case 6
            Return "Pending discharge"
        Default
            Return "unknown"
    End Select
    
End

