' Gambas module file

Public Enum WebViewNone = 2000, WebViewLoaded = 2001
Public Enum UserReqestNone = 3000, UserRequestPlayWithSMPlayer = 3001
Public Enum UserRequestDownloadAsMusic = 3002, UserRequestDownloadAsVideo = 3003
Public Enum UserRequestSetUrl = 3004, UserReqestClearHistory = 3005
Public Enum UserRequestPlayVideo = 3006, UserRequestPlayAudio = 3007, UserRequestStopMpv = 3008
Public Enum DownloaderNone = 4000, DownloaderStart = 4001, DownloaderOngoing = 4002
Public Enum DownloaderEncoding = 4003, DownloaderFinished = 4004, DownloaderErrorOccurred = 4005
Public Enum MpvNone = 5000, MpvStarted = 5001, MpvPlaying = 5002, MpvKilled = 5003
Public Enum MpvErrorOccurred = 5004
Public Enum TimerBasedTextNone = 6000, TimerBasedTextChanged = 6001
Public Enum TimerBasedTextTimeout = 6002, TimerCount = 6003, TimerTimeout = 6004
