' Gambas module file

Property Read Startup As String

Private Const StartupUrl As String = "http://www.tonvid.com/search.php?q=nagato yuki"
Private Const VideoHeaderTonvid As String = "http://www.tonvid.com/info.php?video_id="
Private Const VideoHeaderYouTube As String = "http://www.youtube.com/watch?v="

Public Function GetYoutubeUrl(argUrl As String) As String
    
    Dim yukiUrl As String = MikuruString.Remove(argUrl, VideoHeaderTonvid, "\n")
    
    Return (VideoHeaderYouTube & yukiUrl)
    
End

Public Function IsVideoUrl(argUrl As String) As Boolean
    
    Return (argUrl Begins VideoHeaderTonvid)
    
End

Private Function Startup_Read() As String

    Return StartupUrl

End
