.TH nagato-keycode 1 2, 2018
.SH NAME
nagato-keycode - check keycode
.SH SYNOPSIS
.BR nagato-keycode 
[-h][-v]
.SH DESCRIPTION
check keycode
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-v\fR
show version and exit
.SH LICENSE
nagato-keycode is licensed under S.O.S.License
.SH AUTHORS
takedanemuru takeda.nemuru@yandex.com
