name: nagato-color-chooser
package-name: nagato-color-chooser
id: io.github.takedanemuru.nagato-color-chooser
version: 42.11.5
check-unique: false
short-description: pick color from screen.
long-description: |
    A screen color picking tool for NagatoBox.
    This software is licensed under S.O.S. Lisense.
authors: |
    copyright (c) 2018 takeda.nemuru
web-site: |
    https://takedanemuru.github.io
