' Gambas module file

Public Function GetDeviceName(argProxy As DBusProxy) As String
        
        Return File.Name(argProxy.NativePath)
        
End

Public Function GetIcon(argProxy As DBusProxy) As Picture
        
        Select Case argProxy.technology
                Case 0
                        Return Stock["medium/disconnect"]
                Case 1
                        Return Stock["medium/battery"]
                Default
                        Return Stock["medium/question"]
        End Select
        
End

