' Gambas module file

Public Function Get(argText As String, argFont As Font, argLength As Integer) As String
    
    Dim yukiCount As Integer
    Dim yukiText As String
    
    If argLength >= argFont.TextWidth(argText) Then Return argText
    
    Do
        Inc yukiCount
        If String.Len(argText) = yukiCount Then Return ""
        yukiText = String.Left(argText, String.Len(argText) - yukiCount) & "..."
        If argLength >= argFont.TextWidth(yukiText) Then Return yukiText
    Loop
    
End

Public Function GetFitToHeight(argText As String, argFont As Font, argWidth As Integer, argLimit As Integer) As String
    
    Dim yukiCount As Integer
    Dim yukiText As String
    Dim yukiExtention As String = File.Ext(argText)
    
    If argLimit >= argFont.RichTextHeight(argText, argWidth) Then Return argText
    
    Do
        Inc yukiCount
        If String.Len(argText) = yukiCount Then Return ""
        yukiText = String.Left(argText, String.Len(argText) - yukiCount) & "..." & yukiExtention
        If argLimit >= argFont.RichTextHeight(yukiText, argWidth) Then Return yukiText
    Loop
    
End
