' Gambas module file

Public Sub _call(argIndex As Integer, Optional argIsDay As Boolean = Null) As Integer
    
    If argIsDay <> Null Then
        Return IIf(argIsDay, MikuruWeatherColorDay[argIndex], MikuruWeatherColorNight[argIndex])
    Else If Hour(Now()) >= 6 And If 18 > Hour(Now()) Then
        Return MikuruWeatherColorDay[argIndex]
    Else
        Return MikuruWeatherColorNight[argIndex]
    Endif
    
End