' Gambas module file

Public Sub _get(argIndex As Integer) As Integer
    
    Select Case argIndex
        Case 1 'Clear
            Return Color.Lighter(Color.Gray)
        Case 2  'Fair
            Return Color.Lighter(Color.Gray)
        Case 3  'Partly cloudy
            Return Color.Lighter(Color.Gray)
        Case 4  'Cloudy
            Return Color.Gray
        Case 5  'Rain Showers
            Return Color.DarkBlue
        Case 6  'Rain Showers with Thunder
            Return Color.DarkBlue
        Case 7  'Sleet Showers
            Return Color.Lighter(Color.Gray)
        Case 8  'Snow Showers
            Return Color.Lighter(Color.Gray)
        Case 9  'Rain
            Return Color.DarkBlue
        Case 10 'Heavy Rain
            Return Color.DarkBlue
        Case 11 'Rain and Thunder
            Return Color.DarkBlue
        Case 12 'Sleet
            Return Color.Lighter(Color.Gray)
        Case 13 'Snow
            Return Color.Lighter(Color.Gray)
        Case 14 'Snow with Thunder
            Return Color.Lighter(Color.Gray)
        Case 15 'Fog
            Return Color.Lighter(Color.Gray)
        Case 16 'Clear / Winter Darkness
            Return Color.Lighter(Color.Gray)
        Case 17 'Partly Cloudy / Winter Darkness
            Return Color.Gray
        Case 18 'Rain Showers / Winter Darkness
            Return Color.DarkBlue
        Case 19 'Snow Showers / Winter Darkness
            Return Color.Lighter(Color.Gray)
        Case 20 'Sleet Showers and Thunder
            Return Color.Lighter(Color.Gray)
        Case 21 'Snow Showers and Thunder
            Return Color.Lighter(Color.Gray)
        Case 22 'Rain Showers and Thunder
            Return Color.DarkBlue
        Case 23 'Sleet Showers and Thunder
            Return Color.Lighter(Color.Gray)
        Default 'Unknown
            Return Color.Black
    End Select
    
End
