' Gambas module file

Public Function Get(argPath As String) As String
    
    Dim yukiCount As Integer
    Dim yukiPath As String
    
    If Not Exist(argPath) Then Return argPath
    
    Do
        Inc yukiCount
        With File
            yukiPath = Subst$("&1/&2(&3).&4", .Dir(argPath), .BaseName(argPath), yukiCount, .Ext(argPath))
        End With
        If Not Exist(yukiPath) Then Return yukiPath
    Loop
    
End
