' Gambas module file

Private Function getGenericPath(argPath As String, argIndex As Integer) As String
    
    Dim yukiDirectory As String = File.Dir(argPath)
    Dim yukiBaseName As String = File.BaseName(argPath)
    Dim yukiExtension As String = File.Ext(argPath)
    
    Return Subst("&1/&2(&3).&4", yukiDirectory, yukiBaseName, argIndex, yukiExtension)
    
End

Public Sub _call(argPath As String) As String
    
    Dim yukiCount As Integer = 0
    Dim yukiPath As String
    
    If Not Exist(argPath) Then Return argPath
    
    Do
        Inc yukiCount
        yukiPath = getGenericPath(argPath, yukiCount)
        If Not Exist(yukiPath) Then Return yukiPath
    Loop
    
End
