' Gambas module file

Private $headerSetter As New NagatoHeaderSetter
Private $symbolSetter As New NagatoSymbolSetter

Private Function getBaseTile(argPath As String) As Picture
    
    Select Case MikuruMimeType.GetType(argPath)
        Case MikuruMimeType.TypeDirectory
            Return NagatoIconTileDirectory.Get(argPath)
        Case MikuruMimeType.TypeImage
            Return NagatoThumbnailImage.Get(argPath)
        Case MikuruMimeType.TypePdf
            Return NagatoThumbnailPdf.Get(argPath)
        Case MikuruMimeType.TypeApplication
            Return NagatoIconTileDesktopEntry.Get(argPath)
        Case MikuruMimeType.TypeVideo
            Return NagatoThumbnailVideo.Get(argPath)
        Default
            Return NagatoIconTileOtherFile.Get(argPath)
    End Select
    
End

Public Sub _call(argPath As String, argSelected As Boolean) As Picture
    
    Dim yukiTile As Picture
    
    If Not Access(argPath) Then Return NagatoIconTileBrokenFile.Get(argPath)
    
    yukiTile = getBaseTile(argPath)
    yukiTile = $headerSetter(yukiTile, MikuruTileMode(argPath, argSelected))
    
    Return $symbolSetter(yukiTile, argPath)
    
End
