#!/usr/bin/env python3

#
# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
# |n|a|g|a|t|o|-|c|o|l|o|r|-|c|h|o|o|s|e|r|
# +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
#
# a screen color picking tool for NagatoBox
# this software is licensed under S.O.S. License
#
# copyright (c) 2018 takeda.nemuru <takeda.nemuru@yandex.com>
#

from libnagatocolorchooser.HumanoidInterface import NagatoYuki


if __name__ == "__main__":
    YUKI = NagatoYuki()
    YUKI.N(">...見えてる？")
