' Gambas module file

Public Function GetDesktopFiles(argFullPath As String) As DesktopFile[] 
    
    Return DesktopMime.FromFile(argFullPath).GetApplications()
    
End

Public Function IsAudioFile(argFullPath As String) As Boolean
    
    Return (DesktopMime.FromFile(argFullPath).Type Begins "audio")
    
Catch
    Return False
    
End

Public Function IsImageFile(argFullPath As String) As Boolean
    
    Return (DesktopMime.FromFile(argFullPath).Type Begins "image")
    
Catch
    Return False
    
End
