name: nagato-screenshot
package-name: nagato-screenshot
id: io.github.takedanemuru.nagato-screenshot
version: 0.0.1
check-unique: false
short-description: take a screenshot
long-description: |
    screenshot taking tool for NagatoBox

authors: |
    copyright (c) 2018 takedanemuru
web-site: |
    https://takedanemuru.github.io
