' Gambas module file

Private $userAutoStarts As NagatoAutoStarts
Private $globalAutoStarts As NagatoAutoStarts

Private Sub execAll()
    
    Dim yukiExecuted As String[]
    
    yukiExecuted = $globalAutoStarts.Execute([""], $userAutoStarts)
    $userAutoStarts.Execute(yukiExecuted)
    
End

Public Sub Main()

    $userAutoStarts = New NagatoAutoStarts(User.Home &/ ".config/autostart")
    $globalAutoStarts = New NagatoAutoStarts("/etc/xdg/autostart")
    execAll()

End
