#!/usr/bin/env python3

import os
from libnagatodevelop.Create import NagatoCreate


if __name__ == "__main__":
    yuki_path = os.path.abspath(__file__)
    yuki_dir = os.path.dirname(yuki_path)
    yuki_target_path = os.path.join(yuki_dir, "APPNAME")
    YUKI = NagatoCreate()
    YUKI.Create(yuki_target_path)
