' Gambas module file

Private Function getUTCHour() As Integer
    
    Dim yukiResult As String
    
    Shell Subst$("date -u &1", Quote$("+%k")) To yukiResult
    
    Return CInteger(Replace$(yukiResult, "\n", ""))
    
End

Private Function getUTCMinute() As Integer
    
    Dim yukiResult As String
    
    Shell Subst$("date -u &1", Quote$("+%M")) To yukiResult
    
    Return (CInteger(Replace$(yukiResult, "\n", "")) / 60)
    
End

Public Function IsDay(argLongitude As Float) As Boolean
    
    Dim yukiCurrentTime As Float = getUTCHour() + getUTCMinute() + (argLongitude / 15)
    
    If 18 > yukiCurrentTime And If yukiCurrentTime >= 6 Then
        Return True
    Else
        Return False
    Endif
    
End

Public Function GetLocalTimeStamp(argLongitude As Float) As String
    
    Dim yukiUtcTime As Date = DateAdd(Now(), gb.Hour, CInt(System.TimeZone / 3600))
    Dim yukiLocalTime As Date = DateAdd(yukiUtcTime, gb.Hour, CInt(argLongitude / 15))
    
    Return Format$(yukiLocalTime, "yyyy-mm-ddThh-00-00Z")

End

Public Function IsLater(argTimeStampA As String, argTimeStampB As String) As Boolean
    
    Dim yukiPosition As Integer
    
    For yukiPosition = 1 To String.Len(argTimeStampA)
        If Mid(argTimeStampA, yukiPosition, 1) = Mid(argTimeStampB, yukiPosition, 1) Then
            Continue
        Else If Mid(argTimeStampA, yukiPosition, 1) > Mid(argTimeStampB, yukiPosition, 1) Then
            Return True
        Else
            Return False
        Endif
    Next
    
    Return False
    
End

