' Gambas module file

Private $weekDay As String[] = [("Sun"), ("Mon"), ("Tue"), ("Wed"), ("Thu"), ("Fri"), ("Sat")]

Private Function getYear(argTime As String) As Integer
    
    Return CInt(Mid$(argTime, 1, 4))
    
End

Private Function getMonth(argTime As String) As Integer
    
    Return CInt(Mid$(argTime, 6, 2))
    
End

Private Function getDay(argTime As String) As Integer
    
    Return CInt(Mid$(argTime, 9, 2))
    
End

Private Function getReadableWeekDay(argYear As Integer, argMonth As Integer, argDay As Integer) As String
    
    Dim yukiIndex As Integer = WeekDay(Subst$("&2/&3/&1", argYear, argMonth, argDay))
    
    Return $weekDay[yukiIndex]
    
End

Public Sub _call(argTime As String) As String
    
    Dim yukiYear As Integer = getYear(argTime)
    Dim yukiMonth As Integer = getMonth(argTime)
    Dim yukiDay As Integer = getDay(argTime)
    Dim yukiWeekDay As String = getReadableWeekDay(yukiYear, yukiMonth, yukiDay)
    Dim yukiTime As String = Mid$(argTime, 12, 5)
       
    Return Subst$("&1/&2 (&3) &4", yukiMonth, yukiDay, yukiWeekDay, yukiTime)
    
End
