' Gambas module file

Private Function getHour(argSecond As Integer) As String  
    
    If 3600 > argSecond Then 
         Return ""
    Else
        Return Format$((argSecond Div 3600), "#0:")
    End If
    
End

Private Function getMinute(argSecond As Integer) As String
    
    Return Format$(((argSecond Mod 3600) Div 60), IIf(argSecond > 3600, "00:", "#0:"))
    
End

Private Function getSecond(argSecond As Integer) As String
    
    Return Format$((argSecond Mod 60), "00")
    
End

Public Function _call(argSecond As Float) As String
    
    Dim yukiSecond As Integer = Int(argSecond)
    
    Return Subst$("&1&2&3", getHour(yukiSecond), getMinute(argSecond), getSecond(argSecond))
    
End

