' Gambas module file

Private Sub showMain(argPath As String)
    
    If Not Exist(argPath) Then
        Message.Warning(("YUKI.N > Path not found"), ("OK"))
    Else
        HaruhiImageView.Show()
        HaruhiImageView.SetImage(argPath)
        NagatoSettings.LoadFormSettings(HaruhiImageView)
        Application.MainWindow = HaruhiImageView
    End If
    
End

Private Sub selectPicturePath()
    
    If HaruhiFileChooser.ShowDialog() = MikuruDialog.ResponseSelected Then
        NagatoSettings1.PushToRecentPaths(MikuruDialog.Path)
        showMain(MikuruDialog.Path)
    Else
        ' ToDo
        Debug "Not Selected"
    Endif
    
    ' Dialog.Path = User.Home
    ' Dialog.Title = ("Select Picture")
    ' Dialog.Filter = ["*.png;*.jpg;*.jpeg;*.bmp", "Picture Files"]
    ' 
    ' If Not Dialog.OpenFile(False) Then showMain(Dialog.Path)
    
End

Public Sub Main()
    
    NagatoArguments.Parse()
    
    If NagatoArguments.Path Then
        showMain(NagatoArguments.Path)
    Else
        selectPicturePath()
    End If
    
End
