.TH nagato-audio-indicator 1 5, 2018
.SH NAME
nagato-audio-indicator - audio volume indicator
.SH SYNOPSIS
.BR nagato-audio-indicator 
[-h][-v]
.SH DESCRIPTION
audio volume indicator
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-v\fR
show version and exit
.SH LICENSE
nagato-audio-indicator is licensed under S.O.S.License
.SH AUTHORS
takedanemuru takeda.nemuru@yandex.com
