' Gambas module file

Public Function Get(argIconName As String, Optional argIconSize As Integer = 16) As Picture
    
    Return image.Load(Subst$("picture/blue/&1.png", argIconName)).Stretch(argIconSize, argIconSize).Picture
    
End

Public Function GetCheck(argFlag As Boolean, Optional argIconSize As Integer = 16) As Picture
    
    Return IIf(argFlag, Me.Get("button-check", argIconSize), Null)
    
End

