' Gambas module file

Property Read NagatoBoxConfigDir As String
Property Read NagatoBoxRcPath As String

Private $startNagatoBoxSession As Boolean = False

Private Sub startOpenbox3WithConfigFile()
    
    If Not Exist(Me.NagatoBoxConfigDir) Then Mkdir Me.NagatoBoxConfigDir
    If Not Exist(Me.NagatoBoxRcPath) Then File.Save(File.Load(".hidden/nagato-box-rc.xml"))
    
    Shell Subst$("openbox --config-file &1", Me.NagatoBoxRcPath)
    
End

Private Sub startXdgAutostartDesktopEntries()
    
    Dim yukiDesktopFile As NagatoDesktopFile
    
    For Each yukiDesktopFile In MikuruAutostartDirectory.AutostartDesktopEntries
        Try NagatoDesktopFile.Execute(yukiDesktopFile.Path)
    Next
    
End

Private Sub parsingArguments()
    
    Args.Begin()
        $startNagatoBoxSession = Args.Has("n", "--start-nagato-box", "Start NagatoBox session")
    Args.End()
    
End

Public Sub Main()
    
    parsingArguments()
    If $startNagatoBoxSession Then
        startOpenbox3WithConfigFile()
        startXdgAutostartDesktopEntries()
    Else
        HaruhiMain.Show()
    End If
    
End

Private Function NagatoBoxConfigDir_Read() As String

    Return User.Home &/ ".config/NagatoBox"

End

Private Function NagatoBoxRcPath_Read() As String

    Return Me.NagatoBoxConfigDir &/ "nagato-box-rc.xml"

End
