' Gambas module file

Private $volume As Integer 
Private $loop As Integer
Private $paths As String[]

Private Sub getArgs()
    
    Args.Begin("usage:")
        $volume = Args.GetInteger("v", "volume", "volume",, 65)
        $loop = Args.GetInteger("l", "loop", "loop",, 0)
    $paths = Args.End()
    
End

Private Sub playMusic(argPath As String)
    
    Music.Load(argPath)
    Music.Volume = $volume
    Music.Play($loop)
    
    Do
        If Music.State = Music.Stopped Then Break
        Wait 2
    Loop
    
End

Private Sub playPaths()
    
    Dim yukiPath As String
    
    For Each yukiPath In $paths
        If Not Exist(yukiPath) Then Continue
        If File.Ext(yukiPath) <> "wav" Then Continue
        playMusic(yukiPath)
    Next
    
End

Public Sub Main()

    getArgs()
    
    'for testing
    '$paths = ["choir.wav"]
    
    playPaths()
    
    Quit 0
    
End
