#!/bin/sh -e

set -e


# Automatically added by dhpython:
if which py3compile >/dev/null 2>&1; then
	py3compile -p nagato-terminal 
fi

# End automatically added section


if [ "$1" = "configure" ]; then
	update-alternatives --install /usr/bin/x-terminal-emulator \
	x-terminal-emulator /usr/bin/nagato-terminal 42 \
	--slave /usr/share/man/man1/x-terminal-emulator.1.gz \
	x-terminal-emulator.1.gz /usr/share/man/man1/nagato-terminal.1.gz
fi
