' Gambas module file

Private $args As New NagatoArgs
Private $dbus As New NagatoDBus

Public Sub Main()
    
    $args.Parsing()
    
    If $args.Start Or If Args.Max = 0 Then
        $dbus.EnsureService()
    Else If $args.Category <> "" Then
        $dbus.PrintCategoryMenu($args.Category)
    Else If $args.Available Then
        MikuruArrayTest(NagatoMenuCache.Categories)
    Endif
    
    '$dbus.Test()
    
End
