' Gambas module file

Private $args As New NagatoArgs
Private $dbus As New NagatoDBus

Public Sub Main()
    
    $args.Parsing()
    
    If $args.Start Or If Args.Max = 0 Then
        $dbus.EnsureService()
    Else If $args.Category <> "" Then
        $dbus.PrintCategoryMenu($args.Category)
    Else If $args.Directory <> "" Then
        $dbus.PrintDirectoryMenu($args.Directory)
    Else If $args.File <> "" Then
        $dbus.PrintFileMenu($args.File)
    Else If $args.Available Then
        MikuruArrayTest(NagatoMenuCache.Categories)
    Endif
    
    'NagatoFileCache.Get("/home/takedanemuru/動画/茅原実里/茅原実里10thライブ『向かい風に打たれながら』.webm")
    
End
