' Gambas module file

Property Read Image As Image

Private $image As Image

Private Sub resetImage() 
    
    Dim yukiImage As Image = Image.Load(NagatoSettings.PersonaPath)
    Dim yukiRate As Float = Screen.AvailableWidth / yukiImage.W
    
    $image = yukiImage.Stretch(Screen.AvailableWidth, yukiImage.H * yukiRate)
    
Catch
    $image = Image.Load("pictures/default_persona.png")
    
End

Public Sub Reset()
    
    resetImage()
    
End

Private Function Image_Read() As Image

    If Not Object.IsValid($image) Then resetImage()

    Return $image

End
