' Gambas module file

Public Sub GetAction(argXmlElement As XmlElement) As String
    
    If argXmlElement.Parent.Name = "startupnotify" Then
        Return "startupnotify"
    Else If argXmlElement.Name = "position" Then
        Return ""
    Else If argXmlElement.Name = "finalactions" Then
        Return ""
    Else
        Return argXmlElement.Parent.GetAttribute("name", 1) 
    Endif
    
End

