' Gambas module file

Public Sub _get(argName As String) As String
    
    Select Case argName
        Case "keybind"
            Return "NagatoKeyBind"
        Case "finalactions"
            Return "NagatoFinalActions"
        Case "action", "startupnotify", "position"
            Return "NagatoAction"
        Case "context"
            Return "NagatoMouseContext"
        Case "mousebind"
            Return "NagatoMousebind"
        Default
            Return "NagatoOption"
    End Select
    
End
