' Gambas module file

Public Sub Clean(argSourceString As String, argTargetStrings As String[]) As String
    
    Dim yukiTarget As String
    Dim yukiOutput As String = argSourceString
    
    For Each yukiTarget In argTargetStrings
        yukiOutput = Replace(yukiOutput, yukiTarget, "")
    Next
    
    Return yukiOutput
    
End

Public Sub RemoveUselessLines(argSourceString As String) As String
    
    Dim yukLine As String
    Dim yukiOutput As String
    
    For Each yukLine In Split(argSourceString, "\n", "", True)
        If Me.Clean(yukLine, [" ", "\t", "\n"]) <> "" Then yukiOutput &= (yukLine & "\n")
    Next
    
    Return yukiOutput
    
End

Public Sub GetSanitizedValue(argSource As String) As String
    
    Dim yukiValue As String = Me.Clean(argSource, ["\t", "\n"])
    
    yukiValue = LTrim(yukiValue)
    yukiValue = RTrim(yukiValue)
    
    Return yukiValue
    
End
