' Gambas module file

Private Function getUTCHour() As Integer
    
    Dim yukiResult As String
    
    Shell Subst$("date -u &1", Quote$("+%k")) To yukiResult
    
    Return CInteger(Replace$(yukiResult, "\n", ""))
    
End

Private Function getUTCMinute() As Integer
    
    Dim yukiResult As String
    
    Shell Subst$("date -u &1", Quote$("+%M")) To yukiResult
    
    Return (CInteger(Replace$(yukiResult, "\n", "")) / 60)
    
End

Public Function IsDay(argLongitude As Float) As Boolean
    
    Dim yukiCurrentTime As Float = getUTCHour() + getUTCMinute() + (argLongitude / 15)
    
    yukiCurrentTime = CInt(yukiCurrentTime) Mod 24 + getUTCMinute()
    
    If 18 > yukiCurrentTime And If yukiCurrentTime >= 6 Then
        Return True
    Else
        Return False
    Endif
    
End

