' Gambas module file

Private Function isUnique() As Boolean
    
    Dim yukiDesktopWindow As DesktopWindow
    
    For Each yukiDesktopWindow In Desktop.Windows
        If yukiDesktopWindow.Name = ("nagato-navigator") Then Return False
    Next
    
    Return True
    
End

Public Sub Check()
    
    If Not isUnique() Then 
        Message.Info(("nagato-navigator has been activated."), ("OK"))
        Quit
    Endif
    
End
