' Gambas module file

Public Function GetStringFromInteger(argStateIndex As Integer) As String
    
    Select Case argStateIndex
        Case 0
            Return "Networking state is unknown."
        Case 10
            Return "Networking is inactive and all devices are disabled."
        Case 20
            Return "There is no active network connection."
        Case 30
            Return "Network connections are being cleaned up."
        Case 40
            Return "A network device is connecting to a network and there is no other available network connection."
        Case 50
            Return "A network device is connected, but there is only link-local connectivity."
        Case 60
            Return "A network device is connected, but there is only site-local connectivity."
        Case 70
            Return "A network device is connected, with global network connectivity."
        Default
            Return "Unknown State"
    End Select
    
End
