' Gambas module file

Private Const Service As String = "org.gambas.nagato-files"
Private Const ObjectPath As String = "/org/nagato/files"
Private Const Interface As String = "org.gambas.nagato.files.nagatointerfacedesktop"

Private $dbus As New NagatoDBus

Private Sub callNotify()
    
    If DBus.Session.Applications.Exist(Service) Then ' redirect to nagato-desktop
        With NagatoArgs
            DBus[Service][ObjectPath, Interface].Notify(.App, .Summary, .Body, .Urgency)
        End With
    Else
        HaruhiNotify2.Show()
    Endif
    
End

Public Sub Main()
    
    NagatoArgs.Parsing()
    
    If Args.Max = 0 Then
        $dbus.EnsureService()
    Else If NagatoArgs.Notify Then
        callNotify()
    End If

End
