.TH nagato-gif-viewer 1 2, 2018
.SH NAME
nagato-gif-viewer - gif viewer
.SH SYNOPSIS
.BR nagato-gif-viewer 
[-h][-v]
.SH DESCRIPTION
gif viewer
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-v\fR
show version and exit
.SH LICENSE
nagato-gif-viewer is licensed under S.O.S.License
.SH AUTHORS
takedanemuru takeda.nemuru@yandex.com
