name: APPNAME
package-name: APPNAME
id: id.of.application
version: 0.0.1
check-unique: true
short-description: SHORT_DESCRIPTION
long-description: |
    LONG_DESCRIPTION.
authers: |
    copyright (c) COPYRIGHT_YEAR AUTHOR_NAME
web-site: |
    https://somewhere.foo.bar/baz
