' Gambas module file

Public Function Get(argName As String, Optional argSize As Integer = 2 * MikuruUx.Grid) As Picture
    
    Dim yukiImage As Image = Image.Load(Subst$("Pictures/icons/&1.png", argName)).Stretch(argSize, argSize)
    
    Return yukiImage.Picture
    
End

Public Sub GetNetworkDeviceIcon(argIndex As Integer) As Picture
    
    Select Case NagatoNetworkManager.GetDeviceTypeReadable(argIndex)
        Case "Wireless"
            Return Me.Get("wireless-router")
        Case "Wired"
            Return Me.Get("hard-drive-network")
        Default
            Return Me.Get("question")
    End Select
    
End
