' Gambas module file

Private Function getPolygon(argBaseLine As Integer, argHeight As Integer) As Integer[]
    
    Dim yukiPolygon As New Integer[]
    
    yukiPolygon.Add(4 * MikuruUx.Grid)
    yukiPolygon.Add(argBaseLine)
    yukiPolygon.Add(6 * MikuruUx.Grid)
    yukiPolygon.Add(argBaseLine)
    yukiPolygon.Add(8 * MikuruUx.Grid)
    yukiPolygon.Add(argHeight)
    yukiPolygon.Add(4 * MikuruUx.Grid)
    yukiPolygon.Add(argBaseLine)
    
    Return yukiPolygon
    
End

Private Function getBalloonImage(argHeight As Integer, argWidth As Integer, argPriority As Integer) As Image
    
    Dim yukiBaseImage As New Image(argWidth + 4 * MikuruUx.Grid, argHeight + 8 * MikuruUx.Grid, Color.Transparent)
    Dim yukiBaseLine As Integer = argHeight + 2 * MikuruUx.Grid
    Dim yukiColor As Integer = IIf(argPriority = NagatoNotifyQueue.PriorityCritical, Color.Red, NagatoSettingsPanel.Background)
    
    Paint.Begin(yukiBaseImage)
        Paint.Brush = Paint.Color(yukiColor)
        Paint.Rectangle(0, 0, yukiBaseImage.W, argHeight + 2 * MikuruUx.Grid, 2 * MikuruUx.Grid)
        Paint.Polygon(getPolygon(yukiBaseLine, yukiBaseImage.H))
        Paint.Fill()
    Paint.End()
    
    Return yukiBaseImage
    
End

Public Sub Get(argHeight As Integer, argWidth As Integer, argPriority As Integer) As Image
    
    Return getBalloonImage(argHeight, argWidth, argPriority)
    
End
