' Gambas module file

Public Sub Notify(argPriority As Integer)
    
    Dim yukiSoundPath As String
    Dim yukiPath As String = Temp() & ".wav"
    Dim yukiOutput As String
    
    Select Case argPriority
        Case NagatoNotifyQueue.PriorityHello
            yukiSoundPath = ("sound/notification2.wav")
        Case NagatoNotifyQueue.PriorityCritical
            yukiSoundPath = ("sound/negative-warning.wav")
        Case Else
            yukiSoundPath = ("sound/effect-notify.wav")
    End Select
    
    Copy yukiSoundPath To yukiPath
    
    Exec ["play", yukiPath] 
    
End
