' Gambas module file

Public Sub IsFileTypeToRead(argPath As String) As Integer
    
    If IsDir(argPath) Then
        Return False
    Else If argPath Like "*~" Then ' to ignore back-up files
        Return False
    Else If argPath Like "*.class" Or If argPath Like "*.module" Then
        Return True
    Else If argPath Like "*.form" Then
        Return True
    Else
        Return False
    Endif
    
End
