' Gambas module file

Public Sub Sanitize(argPaths As String[]) As String[]
    
    Dim yukiPath As String
    Dim yukiPaths As New String[]
    
    For Each yukiPath In argPaths
        If MikuruProjectDirectory.IsValid(yukiPath) Then yukiPaths.Add(yukiPath)
    Next
    
    Return yukiPaths.Copy()
    
Catch
    Return Null
    
End

Public Function GetRecents(argPaths As String[], argDirectory As String) As String[]
    
    Dim yukiRecents As String[] = argPaths.Copy()
    Dim yukiTargetIndex As Integer = yukiRecents.Find(argDirectory) ' .Find(value) returns -1 if value not found.
    
    If yukiTargetIndex > -1 Then yukiRecents.Remove(yukiTargetIndex)
    yukiRecents.Add(argDirectory, 0)
    yukiRecents.Resize(30)
    
    Return yukiRecents.Copy()
    
End
