' Gambas module file

Public Function GetName(argParentDirectoryName As String, argTargetDirectoryName As String) As String 
    
    Dim yukiCounter As Integer = 0
    Dim yukiPath As String = argParentDirectoryName &/ argTargetDirectoryName
    
    If Not Exist(yukiPath) Then Return (yukiPath)

    Do 
        Inc yukiCounter
        Debug Subst$("&1(&2)", yukiPath, yukiCounter)
        If Not Exist(Subst$("&1(&2)", yukiPath, yukiCounter)) Then
            Return Subst$("&1(&2)", yukiPath, yukiCounter)
        End If
    Loop
    
End

Public Function Ensure(argPath As String) As String 
    
    Dim yukiCounter As Integer = 0
    
    If Not Exist(argPath) Then Return (argPath)

    Do 
        Inc yukiCounter
        If Not Exist(Subst$("&1(&2)", argPath, yukiCounter)) Then
            Return Subst$("&1(&2)", argPath, yukiCounter)
        End If
    Loop
    
End