' Gambas module file

Public Sub Set(argMode As Integer)
    
    Dim yukiRendarer As Object
    
    Select argMode
        Case MikuruRenderMode.Center
            yukiRendarer = New NagatoWallPaperCenter
        Case MikuruRenderMode.Tile
            yukiRendarer = New NagatoWallpaperTileCenter
        Case MikuruRenderMode.Full
            yukiRendarer = New NagatoWallpaperFull
        Case MikuruRenderMode.Fit
            yukiRendarer = New NagatoWallpaperFit
        Case MikuruRenderMode.Fill
            yukiRendarer = New NagatoWallpaperFill
        Case MikuruRenderMode.TopLeft
            yukiRendarer = New NagatoWallpaperTopLeft
        Case MikuruRenderMode.TopCenter
            yukiRendarer = New NagatoWallpaperTopCenter
        Case MikuruRenderMode.TopRight
            yukiRendarer = New NagatoWallpaperTopRight
    End Select
    
    yukiRendarer.Set(MikuruOriginalImage.Image)
    
End

