' Gambas module file

Private Sub startApplication()
    
    Dim yukiArguments As New NagatoArguments
    
    If yukiArguments.SetLast Then
        NagatoWallpaperSetter.SetLast()
    Else
        HaruhiMain.Show()
        If yukiArguments.Options.Count > 0 Then HaruhiMain.SetPath(yukiArguments.Options[0])
    End If
    
End

Public Sub Main()
    
    MikuruHidden.Ensure()
    'startApplication()
    
    ' NOW Testing
    HaruhiOnScreenDisplay.Show()
    
End
