' Gambas module file

Private Function getOutputPath(argSourcePath As String) As String
    
    Return Temp() & "." & File.Ext(argSourcePath)
    
End

Public Sub Karaoke(argSourcePath As String) As String
    
    Dim yukiOutputPath As String = getOutputPath(argSourcePath)
    
    Exec ["sox", argSourcePath, yukiOutputPath, "oops"] Wait
    
    Message.Info("YUKI.N > Done.", ("OK"))
    
    Return yukiOutputPath
    
Catch
    Return ""
    
End

Public Sub Silence(argSourcePath As String) As String
    
    Dim yukiOutputPath As String = getOutputPath(argSourcePath)
    
    Exec ["sox", argSourcePath, yukiOutputPath, "silence", "1", "0.3", "1%"] Wait
    
    Message.Info("YUKI.N > Done.", ("OK"))
    
    Return yukiOutputPath
    
Catch
    Return ""
    
End

Public Sub Loudness(argSourcePath As String) As String
    
    Dim yukiOutputPath As String = getOutputPath(argSourcePath)
    
    Exec ["sox", argSourcePath, yukiOutputPath, "loudness"] Wait
    
    Message.Info("YUKI.N > Done.", ("OK"))
    
    Return yukiOutputPath
    
Catch
    Return ""
    
End

Public Sub BassBoost(argSourcePath As String) As String
    
    Dim yukiOutputPath As String = getOutputPath(argSourcePath)
    
    Exec ["sox", "-S", argSourcePath, yukiOutputPath, "bass", "+3"] Wait
    
    Message.Info("YUKI.N > Done.", ("OK"))
    
    Return yukiOutputPath
    
Catch
    Return ""
    
End

Public Sub Normalize(argSourcePath As String) As String
    
    Dim yukiOutputPath As String = getOutputPath(argSourcePath)
    
    Exec ["sox", argSourcePath, yukiOutputPath, "norm"] Wait
    
    Message.Info("YUKI.N > Done.", ("OK"))
    
    Return yukiOutputPath
    
Catch
    Return ""
    
End
