#!/usr/bin/env python3
#                         _              _                      _             _ 
# _ __   __ _  __ _  __ _| |_ ___      | |_ ___ _ __ _ __ ___ (_)_ __   __ _| |
#| '_ \ / _` |/ _` |/ _` | __/ _ \ ____| __/ _ \ '__| '_ ` _ \| | '_ \ / _` | |
#| | | | (_| | (_| | (_| | || (_) |____| ||  __/ |  | | | | | | | | | | (_| | |
#|_| |_|\__,_|\__, |\__,_|\__\___/      \__\___|_|  |_| |_| |_|_|_| |_|\__,_|_|
#             |___/                                                             
#
# a multi-grid terminal emulator
# 
# copyright (c) 2017-2018 takeda.nemuru <takeda.nemuru@yandex.com>
# this software is licensed under S.O.S. License.

from libnagatoterminal.HumanoidInterface import NagatoYuki


if __name__ == "__main__":
    YUKI = NagatoYuki()
    YUKI.N(">...見えてる？")
