.TH nagato-terminal 1 August,2017
.SH NAME
nagato-terminal - A terminal emulator
.SH SYNOPSIS
.BR nagato-terminal 
[-h][-d DIRECTORY][-e COMMAND][-v]
.SH DESCRIPTION
Get back background image to terminal emulator !
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.TP
\fB\-d\fR DIRECTORY
set working directory
.TP
\fB\-e\fR COMMAND
execute command
.TP
\fB\-v\fR
show version and exit
.SH LICENSE
nagato-terminal is licensed under S.O.S.License
.SH AUTHERS
takeda.nemuru <takeda.nemuru@yandex.com>
