' Gambas module file

Property Read List As String[]

Public Enum None, DoNow, DoNext, Project, Waiting, Calendar, File, SomeDay, Trash, Fail, Done

Private $list As String[] = ["None", "DoNow", "DoNext", "Project", "Waiting", "Calendar", "File", "SomeDay", "Trash", "Fail", "Done"]

Public Function GetIcon(argIndex As Integer) As Picture
    
    Select Case argIndex
        Case Me.None
            Return Null
        Case Me.DoNow
            Return MikuruIcon.Get("button-play")
        Case Me.DoNext
            Return MikuruIcon.Get("button-pause")
        Case Me.Project
            Return MikuruIcon.Get("folder")
        Case Me.Waiting
            Return MikuruIcon.Get("alarm-clock")
        Case Me.Calendar
            Return MikuruIcon.Get("calendar")
        Case Me.File
            Return MikuruIcon.Get("archive")
        Case Me.SomeDay
            Return MikuruIcon.Get("question")
        Case Me.Trash
            Return MikuruIcon.Get("bin")
        Case Me.Fail
            Return MikuruIcon.Get("exclamation")
        Case Me.Done
            Return MikuruIcon.Get("button-check")
        Default
            Return Null
    End Select
    
End

Private Function List_Read() As String[]

    Return $list

End
