' Gambas module file

Property Read All As String[]

Private Function All_Read() As String[]

    Dim yukiCategories As New String[]
    
    With yukiCategories
        .Add("All")
        .Add("Nagato")
        .Add("Settings")
        .Add("Graphics")
        .Add("Medias")
        .Add("Educations")
        .Add("Networks")
        .Add("Developments")
        .Add("Offices")
        .Add("Games")
        .Add("Utilities")
        .Add("Systems")
        .Add("Kde4")
    End With

    Return yukiCategories

End
