' Gambas module file

Private Sub checkIn(argId As String)
    
    If NagatoDBus.IsUnique() Then 
        NagatoDBus.Register()
        TFEI.CheckIn(argId)
    Else
        NagatoDBus.Proxy.CheckIn(argId)
    End If

End

Private Sub checkOut(argId As String)
    
    If NagatoDBus.IsUnique() Then Return
    
    NagatoDBus.Proxy.CheckOut(argId)
    
End

Private Sub testSequence()
    
    'checkIn("test test")
    
End

Public Sub Main()

    NagatoArgs.Parse()

    If NagatoArgs.CheckOut <> "" Then
        checkOut(NagatoArgs.CheckOut)
    Else If NagatoArgs.CheckIn <> "" Then
        checkIn(NagatoArgs.CheckIn)
    Else If NagatoArgs.All Then
        NagatoTerminalInterface.ShowAll()
    ' Else
    '     normal()
    End If
    
    'testSequence()
    
End
