' Gambas module file

Property Read MenuFileDirectory As String
'Property Read MenuIconsDirectory As String

Private Sub ensureMenuFileDirectory()
    
    If Not Exist(Me.MenuFileDirectory) Then Mkdir Me.MenuFileDirectory
    
End

Private Function MenuFileDirectory_Read() As String

    ensureMenuFileDirectory()

    Return User.Home &/ ".nagato-openbox-menu"

End

' Private Function MenuIconsDirectory_Read() As String
' 
'     ensureMenuFileDirectory()
' 
'     Return Me.MenuFileDirectory &/ "icons"
' 
' End
