' Gambas module file

Public Function Get(argName As String, Optional argSize As Integer = 16) As Picture
    
    Return Image.Load(Subst$("icons/&1.png", argName)).Stretch(argSize, argSize).Picture
    
End

Public Function GetDesktopEntryIcon(argPath As String, Optional argSize As Integer = 16) As Picture
    
    Dim yukiDesktopFile As New DesktopFile(argPath)
    Dim yukiDesktopFileIcon As New NagatoDesktopFileIcon(yukiDesktopFile)
    
    Return yukiDesktopFileIcon.GetIcon(argSize)
    
End

Public Sub _call(argName As String, Optional argSize As Integer = 16) As Picture
    
    Return Image.Load(Subst$("icons/&1.png", argName)).Stretch(argSize, argSize).Picture
    
End
