' Gambas module file

Private $args As New NagatoArgs
Private $terminalInterface As New NagatoTerminalInterface
Private $timer As Timer

Private Sub activateAll()
    
    NagatoObserverFacadeSystem.Start()
    NagatoObserverFacadeNetwork.Start()
    NagatoObserverFacadeHardware.Start()
    
End

Private Sub test()
    
    activateAll()
    $timer = New Timer As "DebugTimer"
    $timer.Enabled = True
    
End

Private Sub normal()
    
    If NagatoDBus.Activated() Then Return

    NagatoDBus.Register()
    activateAll()

End

Public Sub Main()

    $args.Parse()

    If $args.All Then
        If $terminalInterface.EnsureProxy() Then $terminalInterface.ShowAll()
    Else If $args.SystemStatus Then
        If $terminalInterface.EnsureProxy() Then $terminalInterface.ShowSystem()
    Else If $args.NetworkStatus Then
        If $terminalInterface.EnsureProxy() Then $terminalInterface.ShowNetwork()
    Else If $args.HardwareStatus Then
        If $terminalInterface.EnsureProxy() Then $terminalInterface.ShowHardware()
    Else
        normal()
    End If
    
    'test()
    
End

Public Sub DebugTimer_Timer()
    
    ' write something here.
    
End
