' Gambas module file

Private $timer As New Timer As "DebugTimer"

Private Sub activateAll()
    
    NagatoObserverFacadeSystem.Start()
    NagatoObserverFacadeNetwork.Start()
    NagatoObserverFacadeHardware.Start()
    
End

Private Sub test()
    
    activateAll()
    $timer.Enabled = True
    
End

Private Sub normal()
    
    If NagatoDBus.Activated() Then Return

    NagatoDBus.Register()
    activateAll()

End

Public Sub Main()

    'test()
    normal()

End

Public Sub DebugTimer_Timer()
    
    ' write something here.
    
End
