' Gambas module file

Public Function GetDirectory(argPath As String) As String
    
    If Exist(argPath) And If IsDir(argPath) Then Return argPath
    If Exist(File.Dir(argPath)) And If IsDir(File.Dir(argPath)) Then Return File.Dir(argPath)

    Return ""
    
End

Public Function GetFileName(argPath As String) As String
    
    If Me.GetDirectory(argPath) = "" Then Return ""
    If Exist(argPath) And If IsDir(argPath) Then Return ""

    Return File.Name(argPath)
    
End
