' Gambas module file

Public Sub Cut(argTargetDirectory As String, argUriList As String)
    
    Dim yukiPath As String
    
    For Each yukiPath In NagatoDrag2.GetPaths(argUriList)
        If (argTargetDirectory &/ File.Name(yukiPath)) = yukiPath Then Continue
        If Not Exist(yukiPath) Then Continue
        Try Copy yukiPath To MikuruSafePath(argTargetDirectory &/ File.Name(yukiPath))
        If Not Error Then Try Kill yukiPath
    Next
    
    Clipboard.Clear()
    
End

Public Sub Copy(argTargetDirectory As String, argUriList As String)
    
    Dim yukiPath As String
    
    For Each yukiPath In NagatoDrag2.GetPaths(argUriList)
        Try Copy yukiPath To MikuruSafePath(argTargetDirectory &/ File.Name(yukiPath))
    Next
    
End
