name: nagato-web-browser
package-name: nagato-web-browser
id: box.nagato.web-browser
version: 42.10.4
check-unique: true
short-description: a multi-tab web browser based on webkit2.
long-description: |
    a multi-tab web browser based on webkit2.
    This software is licensed under S.O.S. License.
authers: |
    copyright (c) 2017 takeda.nemuru
web-site: |
    https://github.com/takedanemuru/NagatoBox
