' Gambas module file

Private $applicationToRegister As String = ""
Private $applicationToUnregister As String = ""

Private Function isActivated() As Boolean
    
    If DBus.Session.Applications.Exist("org.gambas.nagato.taskmanager") Then
        Return True
    Else
        Return False
    Endif
    
End

Private Function isMainWindowActivated() As Boolean
    
    If HaruhiMain.Closed Then
        Return False
    Else
        Return True
    Endif
    
End

Private Sub pursingArgs()
    
    Dim yukiOptions As String[]
    
    Args.Begin()
        $applicationToRegister = Args.Get("r", "register", "regiter", "application name to register")
        $applicationToUnregister = Args.Get("u", "unregister", "unregiter", "application name to unregister")
    yukiOptions = Args.End()
    
End

Public Sub Main()
    
    pursingArgs()
    
    If $applicationToUnregister <> "" And If isActivated() Then
        NagatoReservation.SignOut($applicationToUnregister)
        If Not NagatoReservation.Has Then Quit 0
    Else If $applicationToRegister <> "" Then
        MikuruObserver.Activate()
        NagatoReservation.SignIn($applicationToRegister)
        If Not HaruhiMain.Closed Then HaruhiMain.Show()
    Else
        HaruhiMain.Show()
    End If
    
End
