name: nagato-text
package-name: nagato-text
id: io.github.takedanemuru.nagato-text
version: 42.12.4
check-unique: false
short-description: text editor for NagatoBox
long-description: |
    basic text pad for NagatoBox
    This software is licensed under S.O.S.License
authors: |
    copyright (c) 2018 takedanemuru
web-site: |
    https://takedanemuru.github.io
