' Gambas module file

Public Sub _get(argPath As String) As Picture
    
    Select Case argPath
        Case NagatoXdg.UserDirs.Desktop
            Return MikuruIcon("desktop")
        Case NagatoXdg.UserDirs.Documents
            Return MikuruIcon("document-edit")
        Case NagatoXdg.UserDirs.Download
            Return MikuruIcon("hard-drive-download")
        Case NagatoXdg.UserDirs.Music
            Return MikuruIcon("music")
        Case NagatoXdg.UserDirs.Pictures
            Return MikuruIcon("image")
        Case NagatoXdg.UserDirs.PublicShare
            Return MikuruIcon("users")
        Case NagatoXdg.UserDirs.Templates
            Return MikuruIcon("ruler")
        Case NagatoXdg.UserDirs.Videos
            Return MikuruIcon("video")
        Default
            Return Null
    End Select
    
End

