' Gambas module file

Property Read ApplicationHidden As String
Property Read ZipFilePath As String
Property Read UnzippedFilePath As String

Public Sub CheckAndCreateAppHiddenDirectory()
    
    If Not Exist(Me.ApplicationHidden) Then
        Mkdir Me.ApplicationHidden
    Endif
    
End

Private Function ApplicationHidden_Read() As String

    Return User.Home &/ ".nagato-bunko"

End

Private Function ZipFilePath_Read() As String

    Return Me.ApplicationHidden &/ "All.zip"

End

Private Function UnzippedFilePath_Read() As String

    Return Me.ApplicationHidden &/ MikuruAozoraBunko.NameForNovelList

End
