' Gambas module file

Property Read StartIdle As Boolean
Property Read Disable As Boolean
Property Read Enable As Boolean
Property Read Config As Boolean

Private $disable As Boolean
Private $enable As Boolean
Private $config As Boolean = False
Private $start As Boolean

Public Sub Parsing()
    
    Args.Begin()
        $start = Args.Has("i", "idle", "start idling nagato-screensaver")
        $disable = Args.Has("d", "disable")
        $enable = Args.Has("e", "enable")
        $config = Args.Has("c", "config", "config")
    Args.End()
    
End

Private Function Disable_Read() As Boolean

    Return $disable

End

Private Function Enable_Read() As Boolean

    Return $enable

End

Private Function Config_Read() As Boolean

    Return $config

End

Private Function StartIdle_Read() As Boolean

    Return $start

End
