' Gambas module file

Property Read Path As String

Private $paths As New String[]

Public Sub Parsing()
    
    Args.Begin("usage")
    
    $paths = Args.End()
    
End

Private Function Path_Read() As String

    Dim yukiPath As String
    
    ' for test
    ' Return "/home/takedanemuru/nagato-youtube-view.gv"
    
    For Each yukiPath In $paths
        If Not Exist(yukiPath) Then Continue
        If DesktopMime.FromFile(yukiPath).Type = "text/vnd.graphviz" Then Return yukiPath
    Next
    
    Return ""
    
End
