' Gambas module file

Public Enum Void = 0
Public Enum FileHeader = 1000, FileNew = 1001, FileRecent = 1002, FileOpen = 1003
Public Enum FileSave = 1004, FileSaveAs = 1005
Public Enum PreviewHeader = 2000, PreviewRefresh = 2001, PreviewExport = 2002
Public Enum SourceHeader = 3000, SourceNew = 3001, SourceChanged = 3002
Public Enum ApplicationHeader = 9000, ApplicationAbout = 9001, ApplicationQuit = 9002
