' Gambas module file

Private Sub activateDesktop()
    
    If Not NagatoDBus.DesktopActivated() Then
        HaruhiDesktop.Show()
    Else
        Message(("YUKI.N > nagato-desktop has been activated."), ("OK"))
    End If
    
End

Private Sub showDesktop()
    
    If Not NagatoDBus.DesktopActivated() Then
        Message(("YUKI.N > nagato-desktop has not been activated."), ("OK"))
    Else
        HaruhiDesktop.ShowDesktop()
    End If
    
End

Private Sub startTestSequence()
    
    'Only For Testing
    activateDesktop()
    'HaruhiXdgConfig.ShowDialog()
    
End

Private Sub startNormalSequence()
    
    If NagatoArguments.DesktopIcons Then
        activateDesktop()
    Else If NagatoArguments.ShowDesktop Then
        showDesktop()
    Else If NagatoArguments.XdgUserDirs Then
        HaruhiXdgConfig.Show()
    Else If NagatoArguments.OpenTrashBin Then
        HaruhiMain.Show()
        TFEI.SetNewTrashBin()
    Else
        HaruhiMain.Show()
    End If

End

Public Sub Main()

    ' NOTE : this call activate NagatoDBSymbol, so do not delete.
    If NagatoDBSymbol.Ready Then Print "YUKI.N > Now we are going to activate nagato-files..." 
    
    NagatoArguments.Parsing()
    MikuruIconTheme.Activate()
    
    NagatoClipBoard.Activate()
    System.FirstDayOfWeek = gb.Sunday

    'startTestSequence()
    startNormalSequence()

End
