' Gambas module file

Public Sub Main()

    ' this call activate NagatoDBSymbol, so do not delete.
    If NagatoDBSymbol.Ready Then Print "YUKI.N > Now we are going to activate files..." 

    Application.Theme = "Numix-Circle"
    
    NagatoArguments.Parsing()
    
    'Only For Testing
    HaruhiDesktop.Show()
    'HaruhiXdgConfig.ShowDialog()
    
    ' If NagatoArguments.DesktopIcons Then
    '     HaruhiDesktop.Show()
    ' Else If NagatoArguments.XdgUserDirs Then
    '     HaruhiXdgConfig.Show()
    ' Else
    '     HaruhiMain.Show()
    ' End If

End
