' Gambas module file

Private Sub activateDesktop()
    
    If Not NagatoDBus.DesktopActivated() Then
        HaruhiDesktop.Show()
    Else
        Message(("YUKI.N > nagato-desktop has been activated."), ("OK"))
    End If
    
End

Public Sub Main()

    ' this call activate NagatoDBSymbol, so do not delete.
    If NagatoDBSymbol.Ready Then Print "YUKI.N > Now we are going to activate files..." 

    Application.Theme = "Numix-Circle"
    
    NagatoArguments.Parsing()
    
    'Only For Testing
    'activateDesktop()
    'HaruhiXdgConfig.ShowDialog()
    
    If NagatoArguments.DesktopIcons Then
        activateDesktop()
    Else If NagatoArguments.XdgUserDirs Then
        HaruhiXdgConfig.Show()
    Else If NagatoArguments.OpenTrashBin Then
        HaruhiMain.Show()
        TFEI.SetNewTrashBin()
    Else
        HaruhiMain.Show()
    End If

End
