' Gambas module file

Public Function GetPosition(argBlock As NagatoBlock) As Integer[]
        
        Dim yukiCounter As Integer
        Dim yukiResult As Integer[] = [argBlock.CenterX, argBlock.CenterY, 0, 0, 0, 0, 0, 0]
        Dim yukiX As Integer
        Dim yukiY As Integer
        Dim yukiTheta As Float
        
        With argBlock
        
        For yukiCounter = 0 To 5 Step 2
                yukiX = .OtherBlocks[yukiCounter]
                yukiY = .OtherBlocks[yukiCounter + 1]
                yukiTheta = Rad((.RotateTimes Mod 4) * -90) 
                yukiResult[yukiCounter + 2] = .CenterX + (yukiX * Cos(yukiTheta) - yukiY * Sin(yukiTheta))
                yukiResult[yukiCounter + 3] = .CenterY + (yukiX * Sin(yukiTheta) + yukiY * Cos(yukiTheta))
        Next

        End With
        
        Return yukiResult
        
End
