' Gambas module file

Property Read Disable As Boolean
Property Read Enable As Boolean
Property Read Show As Boolean

Private $disable As Boolean
Private $enable As Boolean
Private $show As Boolean

Public Sub Parsing()
    
    Args.Begin()
        $disable = Args.Has("d", "disable")
        $enable = Args.Has("e", "enable")
        $show = Args.Has("s", "show")
    Args.End()
    
End

Private Function Disable_Read() As Boolean

    Return $disable

End

Private Function Enable_Read() As Boolean

    Return $enable

End

Private Function Show_Read() As Boolean

    Return $show

End
