' Gambas module file

Public Function GetFromPath(argPath As String) As Picture
    
    Dim yukiMimeType As String = DesktopMime.FromFile(argPath).Type
    
    If yukiMimeType Begins "image" Then
        Return MikuruIcon.Get("image", 16)
    Else If yukiMimeType Begins "audio" Then
        Return MikuruIcon.Get("music", 16)
    Else If yukiMimeType Begins "video" Then
        Return MikuruIcon.Get("video", 16)
    Else 
        Return MikuruIcon.Get("document", 16)
    Endif
    
End

