' Gambas module file

Public Sub _call(argPathFile As String, argPathLine As String)
    
    Dim yukiArray As String[]
    Dim yukiBookmark As String
    Dim yukiResult As String = ""
    
    If Not Exist(argPathFile) Then Return
    
    yukiArray = Split(File.Load(argPathFile), "\n", "", True)
    
    For Each yukiBookmark In yukiArray
        If yukiBookmark = Replace$(MikuruPath.PathToUri(argPathLine), gb.CrLf, "") Then Continue
        yukiResult &= (yukiBookmark & "\n")
    Next
    
    File.Save(argPathFile, yukiResult)
    
End

