#!/usr/bin/env python3
#                         _                          _           _          
# _ __   __ _  __ _  __ _| |_ ___      __      _____| |__       | |__  _ __ 
#| '_ \ / _` |/ _` |/ _` | __/ _ \ ____\ \ /\ / / _ \ '_ \ _____| '_ \| '__|
#| | | | (_| | (_| | (_| | || (_) |_____\ V  V /  __/ |_) |_____| |_) | |   
#|_| |_|\__,_|\__, |\__,_|\__\___/       \_/\_/ \___|_.__/      |_.__/|_|   
#             |___/                                                         
#                             
#  _____      _____  ___ _ __ 
# / _ \ \ /\ / / __|/ _ \ '__|
#| (_) \ V  V /\__ \  __/ |   
# \___/ \_/\_/ |___/\___|_|   
#
#
# a multi-tab web browser.
# copyright (c) 2017-2018 takeda.nemuru <takeda.nemuru@yandex.com>
# This program is free software; you can redistribute it
# and/or modify it under the terms of S.O.S. License.

from libnagatowebbrowser.HumanoidInterface import NagatoYuki


if __name__ == '__main__':
    YUKI = NagatoYuki()
    YUKI.N("> Ready ?")
