' Gambas module file

Property PlaylistName As String

Public Enum ResponseCancel = 1001, ResponseApply = 1002

Private $playlistName As String

Public Sub AddMusic()
    
    Dialog.Title = ("Select music")
    'Dialog.Path = NagatoSettingsMusic.DialogLastPath
    Dialog.Path = Desktop.GetDirectory("MUSIC")
    
    If Not Dialog.OpenFile(True) Then
        NagatoQueue.AddMusics(Dialog.Paths)
    Endif
    
End

Public Sub AddDirectory()
    
    Dialog.Title = ("Select directory")
    Dialog.Path = User.Home
    
    If Not Dialog.SelectDirectory() Then NagatoQueue.ChannelList.AddDirectory(Dialog.Path)
    
End

Private Function PlaylistName_Read() As String

    Return $playlistName

End

Private Sub PlaylistName_Write(Value As String)

    $playlistName = Value

End
