' Gambas module file

Property Read Grid As Integer
Property Read Padding As Integer
Property Read InfoBox As Rect
Property Read InfoBoxInternal As Rect
Property Read ProgressBar As Rect
Property Read CoverArt As NagatoUxCoverArt
Property Read Button As NagatoUxButtons
 
Private $coverArt As New NagatoUxCoverArt
Private $buttons As New NagatoUxButtons
Private $infoBox As New NagatoUxInfoBox
Private $progressBar As New NagatoUxProgressBar

Private Function Grid_Read() As Integer

    Return IIf(Desktop.Resolution > 96, 16, 8)

End

Private Function InfoBox_Read() As Rect
    
    Return $infoBox.External
    
End

Private Function ProgressBar_Read() As Rect

    Return $progressBar.Rect
    
End

Private Function Padding_Read() As Integer

    Return 3 * Me.Grid

End

Private Function InfoBoxInternal_Read() As Rect

    Return $infoBox.Internal

End

Private Function CoverArt_Read() As NagatoUxCoverArt

    Return $coverArt

End

Private Function Button_Read() As NagatoUxButtons

    Return $buttons

End
