' Gambas module file

Public Enum ResponseCancel = 1001, ResponseApply = 1002

Public Sub AddMusic()
    
    Dialog.Title = ("Select music")
    Dialog.Path = Desktop.GetDirectory("MUSIC")
    
    If Not Dialog.OpenFile(True) Then NagatoQueue(MikuruSignal.ListAddMusic, Dialog.Paths)
    
End

Public Sub AddDirectory()
    
    Dialog.Title = ("Select directory")
    Dialog.Path = User.Home
    
    If Not Dialog.SelectDirectory() Then NagatoQueue(MikuruSignal.ListAddDirectory, [Dialog.Path])
    
End
