' Gambas module file

Private $timer As New Timer As "Timer"
Private $feedIndex As Integer = 0
Private $itemIndex As Integer = 0

Private Sub showHeader()
    
    If $itemIndex <> 0 Then Return 
    
    Print Subst("[&1]", NagatoRss[$feedIndex].Title)
    
End

Private Sub showItem()
    
    With NagatoRss[$feedIndex].Items
        Print Subst("&1/&2 &3", $itemIndex + 1, .Count, .[$itemIndex].Title)
    End With
    
End

Private Sub setNextIndex()
    
    Inc $itemIndex
    
    If NagatoRss[$feedIndex].Items.Count = $itemIndex Then
        $itemIndex = 0
        Inc $feedIndex
        If NagatoRss.Feeds.Count = $feedIndex Then $feedIndex = 0
    Endif
    
End

Public Sub _call()
    
     $timer.Enabled = True
    
End

Public Sub Timer_Timer()
    
    If NagatoRss.Feeds.Count = 0 Then Return
    
    showHeader()
    showItem()
    setNextIndex()
    
End

