' Gambas module file

Public Function GetStateString(argType As Integer) As String
    
    Select Case argType
        Case 0
            Return ("Unknown")
        Case 10
            Return ("Disabled")
        Case 20
            Return ("No Active Connections")
        Case 30
            Return ("Being Cleand Up")
        Case 40
            Return ("No Available Connections")
        Case 50
            Return ("Link-Local Connectivity")
        Case 60
            Return ("Site-Local Connectivity")
        Case 70
            Return ("Connected")
    End Select
    
End

