' Gambas module file

Public Sub _call(argDay As Boolean, argWeatherId As Integer, argSize As Integer) As Image
    
    Dim yukiImage As Image 
    
    yukiImage = IIf(argDay, MikuruWeatherIconDay[argWeatherId], MikuruWeatherIconNight[argWeatherId])
    
    Return yukiImage.Stretch(argSize, argSize)
    
End

Public Function GetPath(argDay As Boolean, argWeatherId As Integer) As String
    
    Return IIf(argDay, MikuruWeatherIconPathDay[argWeatherId], MikuruWeatherIconPathNight[argWeatherId])
    
End
