' Gambas module file

Public Sub _get(argIndex As Integer) As Image
    
    Select Case argIndex
        Case 1 'Clear
            Return Image.Load("weather_icons/sunny_night.png")
        Case 2  'Fair (Few Cloud)
            Return Image.Load("weather_icons/cloudy1_night.png")
        Case 3  'Partly Cloudy
            Return Image.Load("weather_icons/cloudy2_night.png")
        Case 4  'Cloudy
            Return Image.Load("weather_icons/cloudy5.png")
        Case 5  'Rain Showers
            Return Image.Load("weather_icons/shower2_night.png")
        Case 6  'Rain Showers with Thunder
            Return Image.Load("weather_icons/tstorm1_night.png")
        Case 7  'Sleet Showers
            Return Image.Load("weather_icons/snow2_night.png")
        Case 8  'Snow Showers
            Return Image.Load("weather_icons/snow3_night.png")
        Case 9  'Rain
            Return Image.Load("weather_icons/light_rain.png")
        Case 10 'Heavy Rain
            Return Image.Load("weather_icons/shower3.png")
        Case 11 'Rain and Thunder
            Return Image.Load("weather_icons/tstorm3.png")
        Case 12 'Sleet
            Return Image.Load("weather_icons/sleet.png")
        Case 13 'Snow
            Return Image.Load("weather_icons/snow5.png")
        Case 14 'Snow with Thunder
            Return Image.Load("weather_icons/snow5.png")
        Case 15 'Fog
            Return Image.Load("weather_icons/fog_night.png")
        Case 16 'Clear / Winter Darkness
            Return Image.Load("weather_icons/sunny_night.png")
        Case 17 'Partly Cloudy / Winter Darkness
            Return Image.Load("weather_icons/cloudy2_night.png")
        Case 18 'Rain Showers / Winter Darkness
            Return Image.Load("weather_icons/shower2_night.png")
        Case 19 'Snow Showers / Winter Darkness
            Return Image.Load("weather_icons/snow2_night.png")
        Case 20 'Sleet Showers and Thunder
            Return Image.Load("weather_icons/sleet.png")
        Case 21 'Snow Showers and Thunder
            Return Image.Load("weather_icons/tstorm1_night.png")
        Case 22 'Rain Showers and Thunder
            Return Image.Load("weather_icons/tstorm2_night.png")
        Case 23 'Sleet Showers and Thunder
            Return Image.Load("weather_icons/snow3_night.png")
        Default 'Unknown
            Return Image.Load("weather_icons/dunno.png")
    End Select
    
End
