' Gambas module file

Private Const Service As String = "org.gambas.nagato-session"
Private Const ObjectPath As String = "/org/nagato/session"
Private Const Interface As String = "org.gambas.nagato.session.nagatointerface"

Private Sub setNagatoSessionDefiendTheme()
    
    Dim yukiProxy As DBusProxy 

    yukiProxy = DBus[Service][ObjectPath, Interface]
    Application.Theme = yukiProxy.IconTheme
    Stock.Refresh()
    
End

Private Sub setGtkDefiendTheme()
    
    Dim yukiOutput As String
    
    Shell "cat ~/.config/gtk-3.0/settings.ini | grep gtk-icon-theme-name" To yukiOutput
    Application.Theme = Replace$(Replace(yukiOutput, "gtk-icon-theme-name=", ""), "\n", "")
    
End

Public Sub Activate()
    
    If DBus.Session.Applications.Exist(Service) Then
        setNagatoSessionDefiendTheme()
    Else If Application.Theme = "?" Or If Application.Theme = "" Then
        setGtkDefiendTheme()
    End If
    
End
