' Gambas module file

Property LastSelectedSymbol As String
Property LastCreatedPath As String

Public Enum ResponseApply = 1001, ResponseCancel = 1002

Private $lastSelectedSymbl As String = ""
Private $lastCreatedPath As String = ""

Private Function LastSelectedSymbol_Read() As String

    Return $lastSelectedSymbl

End

Private Sub LastSelectedSymbol_Write(Value As String)

    $lastSelectedSymbl = Value

End

Private Function LastCreatedPath_Read() As String

    Return $lastCreatedPath

End

Private Sub LastCreatedPath_Write(Value As String)

    $lastCreatedPath = Value

End
