' Gambas module file

Public Sub Main()
    
    MikuruArgs.Parsing()
    
    If MikuruArgs.Start Then
        Try Exec ["xautolock", "-time", NagatoSettings.ScreenSaverIdleMinute, "-locker", NagatoSettings.LockerCommand]
    Else If MikuruArgs.Disable Then
        Try Exec ["xautolock", "-disable"]
    Else If MikuruArgs.Enable Then
        Try Exec ["xautolock", "-enable"]
    Else If MikuruArgs.Show Then
        NagatoScreen.Show()
    Else 'no options 
        HaruhiMain.Show()
    End If
    
End
