' Gambas module file

Public Sub Main()
    
    MikuruArgs.Parsing()
    
    If MikuruArgs.Start Then
        With NagatoSettings
            Try Exec ["xautolock", "-time", .ScreenSaverIdleMinute, "-locker", Quote$(.LockerCommand)]
        End With
    Else If MikuruArgs.Disable Then
        Try Exec ["xautolock", "-disable"]
    Else If MikuruArgs.Enable Then
        Try Exec ["xautolock", "-enable"]
    Else If MikuruArgs.Show Then
        NagatoScreenLocker.Show()
    Else 'no options 
        HaruhiMain.Show()
    End If
    
End
