' Gambas module file

Property Read BoxHeader As Integer
Property Read BoxHighlight As Integer
Property Read BoxNormal As Integer
Property Read BoxVoid As Integer
Property Read Sunday As Integer
Property Read SundayBox As Integer

Public Function HalfTransParent(argColor As Integer) As Integer
    
    Return argColor + 16777216 * 128
    
End

Public Function QuaterTransParent(argColor As Integer) As Integer
    
    Return argColor + 16777216 * 64
    
End

Private Function BoxHighlight_Read() As Integer

    Return Me.QuaterTransParent(Color.Red)

End

Private Function BoxNormal_Read() As Integer

    Return Me.HalfTransParent(Color.Violet)

End

Private Function BoxVoid_Read() As Integer

    Return Color.Violet + 16777216 * 220

End

Private Function BoxHeader_Read() As Integer

    Return Color.Violet + 16777216 * 80

End

Private Function Sunday_Read() As Integer

    Return Color.Pink + 16777216 * 80
    
End

Private Function SundayBox_Read() As Integer

    Return Color.Pink + 16777216 * 220

End
