' Gambas module file

Property Read Name As String
Property Read Pattern As String
Property Read Copyright As String
Property Read NominatimApi As String

Public Sub _get(argLocation As String) As String
    
    Dim yukiLocation As String = Replace$(argLocation, " ", "+")
    
    Return Subst$(Me.NominatimApi, Quote$(yukiLocation))
    
End

Private Function Name_Read() As String

    Return "OpenStreetMap"

End

Private Function Pattern_Read() As String

    Return "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"

End

Private Function Copyright_Read() As String

    Return "© OpenStreetMap contributors"

End

Private Function NominatimApi_Read() As String

    Return "http://nominatim.openstreetmap.org/search?q=&1&format=xml"

End
