' Gambas module file

Private $downloader As New NagatoDownloaderMedia As "Downloader"
Private $locker As NagatoLocker

Public Sub _call(argTitle As String, argUrl As String)
    
    If $locker.IsLocked() Then Return
    
    Dialog.Path = Subst$(NagatoSettings.LastDirectory &/ "&1.mp3", argTitle)
    Dialog.Title = ("Download")
    
    If Dialog.SaveFile() Then Return ' .SaveFile() returns True when NOT selected
    
     $downloader.StartDownloading(argUrl, Dialog.Path)
    NagatoSettings.LastDirectory = File.Dir(Dialog.Path)
    
End

Public Sub Downloader_Finished()
    
    Message.Info(Subst$(("File successfully downloaded to <b>&1</b>"), $downloader.TargetPath), ("OK"))
    $locker.Unlock()
    
End
