' Gambas module file

Property Read Paths As String[]
Property Read About As Boolean

Private $paths As New String[]
Private $about As Boolean

Private Sub sanitize(argPaths As String[])
    
    Dim yukiPath As String
    
    For Each yukiPath In argPaths
        If Exist(yukiPath) Then $paths.Add(yukiPath)
    Next
    
End

Public Sub Parsing()
    
    Dim yukiPaths As String[]
    
    Args.Begin("Usage")
        $about = Args.Has("a", "about", "show about dialog")
    yukiPaths = Args.End()
    
    sanitize(yukiPaths)
    
End

Private Function Paths_Read() As String[]

    Return $paths

End

Private Function About_Read() As Boolean

    Return $about

End
