' Gambas module file

Private Sub getJointName(argNewDirectory As String[]) As String
    
    Dim yukiCount As Integer
    Dim yukiNewName As String = ""
    
    For yukiCount = 0 To argNewDirectory.Max
        yukiNewName &= argNewDirectory[yukiCount]
        If yukiCount = argNewDirectory.Max Then Break
        yukiNewName &= "_"
    Next
    
    Return yukiNewName
    
End

Private Function makeDirectory(argNewDirectory As String) As Boolean
    
    If Exist(argNewDirectory) Then
        Return False
    Else
        Mkdir argNewDirectory
        Return True
    End If
    
End

Private Sub createNewDirectories(argParentDirectory As String, argNewDirectory As String[]) 
    
    Dim yukiJointName As String = (argParentDirectory &/ getJointName(argNewDirectory))
    Dim yukiCount As Integer = 0
    
    If makeDirectory(yukiJointName) Then Return
    
    Do
        Inc yukiCount
        If makeDirectory(Subst$("&1(&2)", yukiJointName, yukiCount)) Then Break
    Loop
    
End

Public Sub Show(argDirectory As String)

    If Not NagatoUserInput.Catch("YUKI.N > Input directory name.") Then Return
    
    createNewDirectories(argDirectory, NagatoUserInput.All)
    
    MikuruDialog.Show("YUKI.N > New directory created. Press [ENTER] to continue.")
    
End
