' Gambas module file

Private $desktopFiles As New DesktopFile[]

Private Function getApplicationNames(argPath As String) As String[]
    
    Dim yukiMimeType As String = DesktopMime.FromFile(argPath).Type
    
    Return MikuruConfFlie.GetItems(MikuruApplications.GlobalMimeList, yukiMimeType).Sort(gb.Natural)
    
End

Private Sub setDesktopFile(argPath As String)
    
    Dim yukiDesktopFile As DesktopFile

    If Not Exist(argPath) Then Return
    
    yukiDesktopFile = New DesktopFile(argPath)
    $desktopFiles.Add(yukiDesktopFile)
    
End

Private Function setDesktopFiles(argPath As String) As String[]
    
    Dim yukiName As String
    
    For Each yukiName In getApplicationNames(argPath)
        setDesktopFile(MikuruApplications.GlobalApplicationDirectory &/ yukiName)
    Next
    
End

Private Sub showApplicationList()
    
    Dim yukiDesktopFile As DesktopFile
    Dim yukiIndex As Integer = 0
    
    For Each yukiDesktopFile In $desktopFiles
        Print Subst$("&1 : &2 (&3)", yukiIndex, yukiDesktopFile.Name, yukiDesktopFile.Comment)
        Inc yukiIndex
    Next
    
    If yukiIndex = 0 Then MikuruDialog.Show("YUKI.N > I couldn't find any application. Press [ENTER] to continue.")
    
End

Private Sub catchCommand(argPath As String)
    
    If Not NagatoUserInput.Catch("YUKI.N > Select application to open...") Then Return
    If Not NagatoUserInput.IsValidIndex($desktopFiles.Max) Then Return
    
    $desktopFiles[NagatoUserInput.Index].Run(argPath)
    
    MikuruDialog.Show("YUKI.N > Press [ENTER] to continue.")
    
End

Public Sub Reset(argPath As String) As Boolean
    
    $desktopFiles.Clear()
    
    setDesktopFiles(argPath)
    
    Return $desktopFiles.Count > 0
    
End

Public Sub Select(argPath As String)
    
    showApplicationList()
    catchCommand(argPath)
    
End
