' Gambas module file

Property Mode As Integer

Public Enum ModeSession, ModeSystem

Private $mode As Integer

Private Function getModeText() As String
    
    If $mode = Me.ModeSession Then
        Return "--session"
    Else
        Return "--system"
    Endif
    
End

Private Function getModeHeader() As String
    
    If $mode = Me.ModeSession Then
        Return "Session://"
    Else
        Return "System://"
    Endif
    
End

Public Sub Get(argService As String, argObjectPath As String) As XmlDocument
    
    Dim yukiOutput As String
    Dim yukiXmlDocument As New XmlDocument
    
    Try Exec ["gdbus", "introspect", getModeText(), "--dest", argService, "--object-path", argObjectPath, "--xml"] To yukiOutput 
    
    yukiXmlDocument.FromString(yukiOutput)
    
    Return yukiXmlDocument
    
End

Public Function IsAccessable(argService As String, argObjectPath As String) As Boolean
    
    If DBus[getModeHeader() & argService]._Introspect(argObjectPath) = "" Then
        Return False
    Else
        Return True
    End If
    
End

Private Function Mode_Read() As Integer

    Return $mode

End

Private Sub Mode_Write(Value As Integer)

    $mode = Value

End
