' Gambas module file

Public Sub _call(argPath As String) As String
    
    Dim yukiCount As Integer 
    Dim yukiPath As String
    
    If Not Exist(argPath) Then Return argPath
    
    Do
         Inc yukiCount
         yukiPath = Subst$("&1/&2(&3).&4", File.Dir(argPath), File.BaseName(argPath), yukiCount, File.Ext(argPath))
         If Not Exist(yukiPath) Then Return yukiPath
    Loop
    
End
