' Gambas module file

Public Function ConversionRequired(argSourcePath As String, argTargetPath As String) As Boolean
    
    With MikuruMimeType
        If Not .IsMediaFile(argSourcePath) Then Return False
        If File.Ext(argTargetPath) = File.Ext(argSourcePath) Then Return False 
    End With
    
    Return True
    
End

Public Sub ConvertFile(argSourcePath As String, argTargetPath As String)
    
    Exec ["avconv", "-i", argSourcePath, argTargetPath]
    
End
