' Gambas module file

Public Enum TypeVoid, TypeDirectory, TypeApplication, TypeFile, TypeClock, TypeRss, TypeSysmon, TypeTrashBin

Public Function GetType(argIconView As IconView) As Integer
    
    If Not Object.IsValid(argIconView.Item) Then
        Return Me.TypeVoid
    Else If IsDir(argIconView.Item.Key) Then
        Return Me.TypeDirectory
    Else If MikuruMimeType.GetType(argIconView.Item.Key) = MikuruMimeType.TypeApplication Then
        Return Me.TypeApplication
    Else If argIconView.Item.Key = NagatoDesktop.SpecialKeyClock Then
        Return Me.TypeClock
    Else If argIconView.Item.Key = NagatoDesktop.SpecialKeySystemMonitor Then
        Return Me.TypeSysmon
    Else If argIconView.Item.Key = NagatoDesktop.SpecialKeyRssFeeder Then
        Return Me.TypeRss
    Else If argIconView.Item.Key = NagatoDesktop.SpecialKeyTrashBin Then
        Return Me.TypeTrashBin
    Else
        Return Me.TypeFile
    Endif
    
End
