' Gambas module file

Private Function getBalloonImage(argHeight As Integer, argWidth As Integer) As Image
    
    Dim yukiBaseImage As New Image(argWidth + 2 * MikuruUx.Grid, argHeight + 8 * MikuruUx.Grid, Color.Transparent)
    Dim yukiBaseLine As Integer = argHeight + 2 * MikuruUx.Grid
    
    Paint.Begin(yukiBaseImage)
        With MikuruUx
            Paint.Brush = Paint.Color(NagatoSettingsPanel.Background)
            Paint.Rectangle(0, 0, yukiBaseImage.W, argHeight + 2 * MikuruUx.Grid, 2 * MikuruUx.Grid)
            Paint.Polygon([4 * .Grid, yukiBaseLine, 6 * .Grid, yukiBaseLine, 8 * .Grid, yukiBaseImage.H, 4 * .Grid, yukiBaseLine])
            Paint.Fill()
        End With
    Paint.End()
    
    Return yukiBaseImage
    
End

Public Sub Get(argText As String) As Image
    
    Dim yukiTextWidth As Integer = Min(HaruhiBalloon.Font.RichTextWidth(argText), 40 * MikuruUx.Grid)
    Dim yukiTextHeight As Integer = HaruhiBalloon.Font.RichTextHeight(argText, yukiTextWidth) 
    
    Return getBalloonImage(yukiTextHeight, yukiTextWidth)
    
End
