' Gambas module file

Private Const ServiceName As String = "org.gambas.nagato.session"
Private Const ObjectPath As String = "/org/nagato/session"
Private Const InterfaceName As String = "org.gambas.nagato.session.nagatointerface"

Public Sub Set()
    
    Dim yukiIconTheme As String
    
    If DBus.Session.Applications.Exist(ServiceName) Then
        Application.Theme = DBus[ServiceName][ObjectPath, InterfaceName].IconTheme
    Endif
    
End
