' Gambas module file

Public Sub Archive(argSelection As String[])
    
    argSelection.Add("nagato-archiver", 0)
    
    Try Exec argSelection
    
End

Public Sub Clone(argCurrentDirectory As String, argSelection As String[])
    
    Dim yukiPath As String
    
    For Each yukiPath In argSelection
        If Not Exist(yukiPath) Then Continue
        Try Copy yukiPath To MikuruPath.GetSafePathName(yukiPath)
    Next
    
End

Public Sub BlankText(argCurrentDirectory As String)
    
    If Not Exist(argCurrentDirectory) Then Return
    File.Save(MikuruPath.GetSafePathName(argCurrentDirectory &/ ("blank.text")), "")
    
End

Public Sub NewDirectory(argCurrentDirectory As String)
    
    If Not Exist(argCurrentDirectory) Then Return
    HaruhiNewDirectory.SetPath(argCurrentDirectory &/ ("New directory"))
    HaruhiNewDirectory.ShowDialog()
    
End
