' Gambas module file

Public Sub Exec(argPath As String) 
    
    Dim yukiDesktopFile As DesktopFile
    Dim yukiMimeType As String = DesktopMime.FromFile(argPath).Type
    
    If Not Exist(argPath) Then
        Return
    Else If yukiMimeType = "application/x-desktop" Then
        yukiDesktopFile = New DesktopFile(argPath)
        yukiDesktopFile.Run("")
    Else
        With MikuruApplications
            yukiDesktopFile = New DesktopFile(.GlobalApplicationDirectory & .GetDefaultDesktopFiles(argPath)[0])
        End With
        Try yukiDesktopFile.Run(argPath)
    End If
    
Catch
    Debug "I can't open..."
    Return
    
End

Public Sub TrashDirectory(argPath As String)
    
    Dim yukiMessage As String = ("YUKI.N > This directory contains some file. Are you sure to delete this directory?")
    
    If Dir(argPath).Count > 0 Then 
        If Message.Warning(yukiMessage, ("Cancel"), ("Delete")) = 1 Then Return
    End If
    
    Try Shell Subst$("trash &1", Quote$(argPath))
    
End

Public Sub TrashFile(argPath As String)
    
    Try Shell Subst$("trash &1", Quote$(argPath))
    
End
