' Gambas module file

Public Function GetPathToOpen() As String
    
    Dialog.Title = ("Open File")
    Dialog.Path = User.Home
    If Dialog.OpenFile(False) Then Return ""
    
    Return Dialog.Path
    
End

Public Function GetPathToSave() As String
    
    Dialog.Title = ("Save File")
    Dialog.Path = User.Home &/ "your_text.txt"
    If Dialog.SaveFile() Then Return ""
    
    Return Dialog.Path
    
End
