' Gambas module file

Public Sub _call()
    
    Dim yukiConfgGtk2 As New NagatoConfigFile(NagatoSettings.PathGtk2)
    Dim yukiConfgGtk3 As New NagatoConfigFile(NagatoSettings.PathGtk3)
    Dim yukiConfgGtkTest As New NagatoConfigFile(User.Home &/ "gtkrc-2.0test")

    yukiConfgGtkTest["gtk-theme-name"] = "NumixWhite3.8"
    
    Debug yukiConfgGtkTest["gtk-theme-name"]
    Debug yukiConfgGtk3["gtk-theme-name"] = yukiConfgGtk2["gtk-theme-name"]
    
End
