' Gambas module file

Public Const KeyType As String = "type"
Public Const KeyName As String = "name"
Public Const KeyLines As String = "lines"
Public Const KeyLinesWithoutVoid As String = "withoutvoid"

Public Function _get(argIndex As Integer) As String
    
    Select Case argIndex
        Case 0
            Return MikuruColumn.KeyType
        Case 1
            Return MikuruColumn.KeyName
        Case 2
            Return MikuruColumn.KeyLines
        Case 3
            Return MikuruColumn.KeyLinesWithoutVoid
        Default
            Return ""
    End Select
    
End