' Gambas module file

Public Function Justify(argImage As Image, Optional argSize As Integer = NagatoSettingsTile.Size) As Image
    
    Dim yukiBaseImage As New Image(argSize, argSize, Color.Transparent)
    Dim yukiRate As Float = Max(argSize / argImage.H, argSize / argImage.W)
    Dim yukiThumbnail As Image = argImage.Stretch(argImage.W * yukiRate, argImage.H * yukiRate)
    
    Paint.Begin(yukiBaseImage)
        Paint.DrawImage(yukiThumbnail, (argSize - yukiThumbnail.W) / 2, (argSize - yukiThumbnail.H) / 2)    
    Paint.End()
    
    Return yukiBaseImage
    
End

