' Gambas module file

Private $directoryTile As New NagatoTileDirectory
Private $applicationTile As New NagatoTileApplication
Private $fileTile As New NagatoTileFile
Private $voidTile As New NagatoTileVoid
Private $brokenTile As New NagatoTileBroken
Private $lostDirectoryTile As New NagatoTileLostDirectory

Private Function getThumbnailImage(argPath As String, argSelected As Boolean) As Picture
    
    Dim yukiPicture As Picture = NagatoThumbnailImage.Get(argPath, argSelected)
    
    Return yukiPicture
    
End

Public Sub _call(argPath As String, argSelected As Boolean) As Picture
    
    If Not Access(argPath) Then Return $brokenTile(argPath, argSelected)
    
    With MikuruMimeType
        Select Case .GetType(argPath)
            Case .TypeDirectory
                Return $directoryTile(argPath, argSelected)
            Case .TypeImage
                Return getThumbnailImage(argPath, argSelected)
            Case .TypePdf
                Return NagatoThumbnailPdf.Get(argPath, argSelected)
            Case .TypeApplication
                Return $applicationTile(argPath, argSelected)
            Case .TypeVideo
                Return NagatoThumbnailVideo.Get(argPath, argSelected)
            Default
                Return $fileTile(argPath, argSelected)
        End Select
    End With
    
End

Public Function GetNotFoundTile() As Picture
    
    Return $voidTile("", False)
    
End

Public Function GetLostDirectoryTile() As Picture
    
    Return $lostDirectoryTile("", False)
    
End

Public Function GetBrokenTile() As Picture
    
    Return $brokenTile("", False)
    
End
