' Gambas module file

Private Sub getFileIconPicture(argPath As String, argSelected As Boolean) As Picture
    
    Select Case MikuruMimeType.GetType(argPath)
        Case MikuruMimeType.TypeImage
            Return MikuruImageThumbnail.Get(argPath, argSelected)
        Case MikuruMimeType.TypeApplication
            Return MikuruTile.GetApplicationTile(argPath, argSelected)
        Default
            Return MikuruTile.GetFileTile(argPath, argSelected)
    End Select

End

Public Function Get(argPath As String, argSelected As Boolean) As Picture
    
    If IsDir(argPath) Then
        Return MikuruTile.GetDirectoryTile(argPath, argSelected)
    Else 'IsFile
        Return getFileIconPicture(argPath, argSelected)
    Endif
    
End

