' Gambas module file

Private $directoryTile As New NagatoTileDirectory
Private $applicationTile As New NagatoTileApplication
Private $fileTile As New NagatoTileFile
Private $voidTile As New NagatoTileVoid
Private $brokenTile As New NagatoTileBroken
Private $lostDirectoryTile As New NagatoTileLostDirectory
Private $symbolSetter As New NagatoSymbolSetter

Public Sub _call(argPath As String, argSelected As Boolean) As Picture
    
    Dim yukiTile As Picture
    
    If Not Access(argPath) Then Return $brokenTile(argPath, argSelected)
    
    Select Case MikuruMimeType.GetType(argPath)
        Case MikuruMimeType.TypeDirectory
            yukiTile = $directoryTile(argPath, argSelected)
        Case MikuruMimeType.TypeImage
            yukiTile = NagatoThumbnailImage.Get(argPath, argSelected)
        Case MikuruMimeType.TypePdf
            yukiTile = NagatoThumbnailPdf.Get(argPath, argSelected)
        Case MikuruMimeType.TypeApplication
            yukiTile = $applicationTile(argPath, argSelected)
        Case MikuruMimeType.TypeVideo
            yukiTile = NagatoThumbnailVideo.Get(argPath, argSelected)
        Default
            yukiTile = $fileTile(argPath, argSelected)
    End Select
    
    Return $symbolSetter(yukiTile, argPath)
    
End

Public Function GetNotFoundTile() As Picture
    
    Return $voidTile("", False)
    
End

Public Function GetLostDirectoryTile() As Picture
    
    Return $lostDirectoryTile("", False)
    
End

Public Function GetBrokenTile() As Picture
    
    Return $brokenTile("", False)
    
End
