' Gambas module file

Property Read Path As String
Property Read PathOriginalImage As String
Property Read PathModefiedImage As String
Property Read DesktopType As String

Private $desktopType As String

Private Sub saveImage(argPath As String)
    
    Dim yukiImage As Image = Image.Load("Pictures/default.jpg")
    
    yukiImage.Save(argPath, 100)
    
End

Private Sub setDesktopType()
    
    Dim yukiDesktopType As String
    
    Shell "printenv | grep XDG_SESSION_DESKTOP=" To yukiDesktopType
    
    yukiDesktopType = Replace$(yukiDesktopType, "XDG_SESSION_DESKTOP=", "")
    $desktopType = Replace$(yukiDesktopType, "\n", "")
    
End

Public Sub Ensure()
    
    setDesktopType()
    
    If Not Exist(Me.Path) Then Mkdir Me.Path
    If Not Exist(Me.PathOriginalImage) Then saveImage(Me.PathOriginalImage)
    If Not Exist(Me.PathModefiedImage) Then saveImage(Me.PathModefiedImage)
    
End

Private Function Path_Read() As String

    Return User.Home &/ ".nagato-wallpaper" &/ $desktopType

End

Private Function PathOriginalImage_Read() As String

    Return Me.Path &/ "original.png"

End

Private Function PathModefiedImage_Read() As String

    Return Me.Path &/ "modefied.png"

End

Private Function DesktopType_Read() As String

    Return $desktopType

End
