' Gambas module file

Private Const ServiceName As String = "org.gambas.nagato.session"
Private Const ObjectPath As String = "/org/nagato/session"
Private Const InterfaceName As String = "org.gambas.nagato.session.nagatointerface"

Public Sub Set()
    
    Dim yukiApplications As String[] = DBus.Session.Applications
    
    Debug yukiApplications.Count
    
    If yukiApplications.Exist(ServiceName) Then
        Try Application.Theme = DBus[ServiceName][ObjectPath, InterfaceName].IconTheme
    Endif
    
End
