' Gambas module file

Public Sub GetSizeText(argPath As String) As String
    
    Dim yukiStat As Stat = Stat(argPath)
    
    If yukiStat.Type = gb.Directory Then Return ("")
    If (2 ^ 10) > yukiStat.Size Then Return Format$(yukiStat.Size, "#,### Byte")
    If (2 ^ 20) > yukiStat.Size Then Return Format$((yukiStat.Size / (2 ^ 10)), "#,###.## KiB")
    If (2 ^ 30) > yukiStat.Size Then Return Format$((yukiStat.Size / (2 ^ 20)), "#,###.## MiB")
    If (2 ^ 40) > yukiStat.Size Then Return Format$((yukiStat.Size / (2 ^ 30)), "#,###.## GiB")
    If (2 ^ 50) > yukiStat.Size Then Return Format$((yukiStat.Size / (2 ^ 40)), "#,###.## TiB")
    If (2 ^ 60) > yukiStat.Size Then Return Format$((yukiStat.Size / (2 ^ 50)), "#,###.## PiB")
    
    Return "?"
    
End

Public Sub GetMimeTypeText(argPath As String) As String
    
    If IsDir(argPath) Then Return "inode/directory"
    
    Return DesktopMime.FromFile(argPath).Type
    
End
