' Gambas module file

Public Sub GetFileIcon(argPath As String, Optional argSize As Integer = 16) As Picture
    
    Return Desktop.GetFileIcon(argPath, argSize)
    
End

Public Sub GetDirectoryIcon(argName As String) As Picture
    
    Select Case argName
        Case "DESKTOP"
            Return Me["desktop"]
        Case "DOCUMENTS"
            Return Me["document-edit"]
        Case "DOWNLOAD"
            Return Me["hard-drive-download"]
        Case "MUSIC"
            Return Me["music"]
        Case "PICTURES"
            Return Me["image"]
        Case "PUBLICSHARE"
            Return Me["users"]
        Case "TEMPLATES"
            Return Me["ruler"]
        Case "VIDEOS"
            Return Me["video"]
        Default
            Return Null
    End Select
    
End

Public Sub _get(argIconName As String, Optional argSize As Integer = 16) As Picture
    
    Dim yukiImage As Image = Image.Load(Subst$("Pictures/Icons/&1.png", argIconName))
    
    Return yukiImage.Stretch(argSize, argSize).Picture
    
End
