' Gambas module file

Public Sub GetChildrenFile(argDirectory As String, argShowHidden As Boolean) As String[]
    
     Dim yukiPaths As String[]
     Dim yukiPattern As String = IIf(argShowHidden, "*", "[^.]*")
     
     yukiPaths = Dir(argDirectory, yukiPattern, gb.File).Sort(gb.IgnoreCase + gb.Natural)
    
    Return yukiPaths
    
End

Public Sub GetChildrenDirectory(argDirectory As String, argShowHidden As Boolean) As String[]
    
     Dim yukiPaths As String[]
     Dim yukiPattern As String = IIf(argShowHidden, "*", "[^.]*")
     
     yukiPaths = Dir(argDirectory, yukiPattern, gb.Directory).Sort(gb.IgnoreCase + gb.Natural)
    
    Return yukiPaths
    
End

Public Function UrlToPath(argUrl As String) As String
    
    If String.InStr(argUrl, " ") > 0 Then argUrl = String.Left(argUrl, String.InStr(argUrl, " ") - 1)
    argUrl = Replace$(argUrl, "file://", "")
    argUrl = URL.Decode(argUrl)
    
    Return argUrl
    
End

Private Function uriEncode(argSource As String) As String
    
    Dim yukiLine As String
    Dim yukiResult As String
    
    For Each yukiLine In Split(argSource, "/", "", True)
        yukiResult &= ("/" & URL.Encode(yukiLine))
    Next
    
    Return yukiResult
    
End

Public Function PathToUri(argPath As String) As String
    
    Dim yukiPath As String
    Dim yukiResult As String
    
    yukiPath = Replace(argPath, " ", "NagatoSpaceEncodeFlag")
    yukiResult = ("file://" & uriEncode(yukiPath) & gb.CrLf)
    yukiResult = Replace(yukiResult, "NagatoSpaceEncodeFlag", "%20")
    
    Return yukiResult
    
End
