' Gambas module file

Property Read IconSize As Integer
Property Read Margin As Integer
Property Read HeaderHeight As Integer
Property Read IconGridSize As Integer

Private Const Unit As Integer = 8

Private Function IconSize_Read() As Integer

    Return 2 * Unit

End

Private Function Margin_Read() As Integer

    Return 2 * Unit

End

Private Function HeaderHeight_Read() As Integer

    Return 4 * Unit

End

Private Function IconGridSize_Read() As Integer

    Return 3 * Unit

End
