' Gambas module file

Property Read Global As String
Property Read GlobalMimeList As String
Property Read KDE4 As String
Property Read Local As String
Property Read LocalDefaultList As String
Property Read GlobalDefaultList As String

Private Function Global_Read() As String

    Return "/usr/share/applications"

End

Private Function KDE4_Read() As String

    Return "/usr/share/applications/kde4"

End

Private Function Local_Read() As String

    Return User.Home &/ ".local/share/applications/"

End

Private Function GlobalMimeList_Read() As String

    Return "/usr/share/applications/mimeinfo.cache"

End

Private Function LocalDefaultList_Read() As String

    Return User.Home &/ ".local/share/applications/mimeapps.list"

End

Private Function GlobalDefaultList_Read() As String

    Return "/usr/share/applications/defaults.list"

End
