' Gambas module file

Private Sub runDesktopFile(argPath As String)
    
    Dim yukiDesktopFile As New DesktopFile(argPath)
    Dim yukiCommandArray As String[] = Split(yukiDesktopFile.Exec, " ", "")
    
    Try Shell yukiCommandArray[0]
    
End

Private Sub openFile(argPath As String)
    
    Dim yukiDesktopFile As DesktopFile
    
    With MikuruApplications
            yukiDesktopFile = New DesktopFile(.GlobalApplicationDirectory & .GetDefaultDesktopFiles(argPath)[0])
    End With
    
    Try yukiDesktopFile.Run(argPath)
    
Catch
    Debug "I can't open..."
    Return
    
End

Public Sub Exec(argPath As String) 
    
    Dim yukiMimeType As String = DesktopMime.FromFile(argPath).Type
    
    If Not Exist(argPath) Then
        Return
    Else If yukiMimeType = "application/x-desktop" Then
        runDesktopFile(argPath)
    Else
        openFile(argPath)
    End If
    
End

Public Function GetFileSizeText(argPath As String) As String
    
    Return MikuruFileSize.GetFileSizeText(argPath)
    
End

Public Function GetTimeDifferenceText(argDate As Date) As String
    
    Return MikuruFileTimeDiff.GetTimeDifferenceText(argDate)
    
End
