' Gambas module file

Public Function GetFileSizeText(argPath As String) As String
    
    Return File.FormatSize(Stat(argPath).Size, True)
    
End

Public Function GetDirectorySizeText(argDirectory As String) As String
    
    Dim yukiPath As String
    Dim yukiSize As Long
    
    
    For Each yukiPath In Dir(argDirectory)
        If Not Exist(argDirectory &/ yukiPath) Then Continue
        Try yukiSize += Stat(argDirectory &/ yukiPath).Size
    Next
    
    Return File.FormatSize(yukiSize, True)
    
End
