' Gambas module file

Public Sub CopyUriList(argTargetDirectory As String, argUriList As String)
    
    Dim yukiPath As String
    
    For Each yukiPath In NagatoDrag2.GetPaths(argUriList)
        Debug yukiPath
        Try Copy yukiPath To MikuruPath.GetSafePathName(argTargetDirectory &/ File.Name(yukiPath))
    Next
    
End

Public Sub MoveTo(argPaths As String[])
    
    Dim yukiPath As String
    
    Dialog.Title = ("Move To ...")
    
    If Not Dialog.SelectDirectory() Then
        For Each yukiPath In argPaths
            Try Move yukiPath To MikuruPath.GetSafePathName(Dialog.Path &/ File.Name(yukiPath))
        Next
    Endif
    
End

Public Sub CopyTo(argPaths As String[])
    
    Dim yukiPath As String
    
    Dialog.Title = ("Move To ...")
    
    If Not Dialog.SelectDirectory() Then
        For Each yukiPath In argPaths
            Try Copy yukiPath To MikuruPath.GetSafePathName(Dialog.Path &/ File.Name(yukiPath))
        Next
    Endif
    
End

Public Sub Remove(argPaths As String[])
    
    Dim yukiPath As String
    
    For Each yukiPath In argPaths
        MikuruFile.TrashFile(yukiPath)
    Next
    
End
