' Gambas module file

Private $arguments As New NagatoArguments

Private Sub checkIn(argId As String)
    
    If NagatoDBus.IsUnique() Then 
        NagatoDBus.Register()
        TFEI.CheckIn(argId)
    Else
        NagatoDBus.Proxy.CheckIn(argId)
    End If

End

Private Sub checkOut(argId As String)
    
    If NagatoDBus.IsUnique() Then Return
    
    NagatoDBus.Proxy.CheckOut(argId)
    
End

Private Sub normalSequence()
    
    If $arguments.CheckIn <> "" Then
        checkIn($arguments.CheckIn)
    Else If $arguments.CheckOut <> "" Then
        checkOut($arguments.CheckOut)
    Else If $arguments.List Then
        MikuruCuiList()
    Else If $arguments.Add <> "" Then
        MikuruAddNewFeed($arguments.Add, $arguments.Name)
    Else If $arguments.Remove <> "" Then
        NagatoSettings.RemoveFeed($arguments.Remove)
    Else
        checkIn("nagato-rss-daemon")
        MikuruCuiTicker()
    Endif
    
End

Public Sub Main()

    $arguments.Parse()
    normalSequence()
    
    ' For Testing.
    'MikuruCuiList()
    'MikuruAddNewFeed("http://rss.cnn.com/rss/edition_technology.rss", "CNN Technology News")
    
End
