' Gambas module file

Public Function GetImage(argPercentage As Integer, Optional argSize As Integer) As Image
    
    Dim yukiImage As Image
    
    Select Case argPercentage
        Case 0 To 10
            yukiImage = Image.Load("battery_icons/battery_009.png")
        Case 11 To 20
            yukiImage = Image.Load("battery_icons/battery_008.png")
        Case 21 To 30
            yukiImage = Image.Load("battery_icons/battery_001.png")
        Case 31 To 40
            yukiImage = Image.Load("battery_icons/battery_002.png")
        Case 41 To 50
            yukiImage = Image.Load("battery_icons/battery_003.png")
        Case 51 To 60
            yukiImage = Image.Load("battery_icons/battery_004.png")
        Case 61 To 70
            yukiImage = Image.Load("battery_icons/battery_005.png")
        Case 71 To 80
            yukiImage = Image.Load("battery_icons/battery_006.png")
        Case 81 To 90
            yukiImage = Image.Load("battery_icons/battery_007.png")
        Case 91 To 100
            yukiImage = Image.Load("battery_icons/battery_010.png")
    End Select
    
    If argSize Then yukiImage = yukiImage.Stretch(argSize, argSize)
    
    Return yukiImage
    
End

