' Gambas module file

Private Function getDirectory() As String
    
    Dim yukiPath As String = Desktop.CacheDir &/ Application.Name
    
    If Not Exist(yukiPath) Then Mkdir yukiPath
    
    Return yukiPath
    
End

Public Sub Initialize()
    
    With WebSettings
        .Cache.Enabled = True
        .[.PluginsEnabled] = NagatoSettings.PluginsEnabled
        .[.JavascriptEnabled] = NagatoSettings.JavaScriptEnabled
        .[.JavascriptCanOpenWindows] = True
        .[.JavascriptCanAccessClipboard] = False
        .[.JavaEnabled] = False
        .[.DeveloperExtrasEnabled] = False
        .[.PrivateBrowsingEnabled] = True
        .IconDatabase.Path = getDirectory()
    End With
    
End
