' Gambas module file

Private Function getDirectory() As String
    
    Dim yukiPath As String = User.Home &/ ".nagato-web"
    
    If Not Exist(yukiPath) Then Mkdir yukiPath
    
    Return yukiPath
    
End

Public Sub Initialize()
    
    With WebSettings
        .Cache.Enabled = True
        .[.PluginsEnabled] = NagatoSettings.PluginsEnabled
        .[.JavascriptEnabled] = NagatoSettings.JavaScriptEnabled
        .[.JavascriptCanOpenWindows] = True
        .IconDatabase.Path = getDirectory()
    End With
    
End
