' Gambas module file

Private Sub testSequence()
    
    'NagatoConverter()
    HaruhiMain.ShowNonFullscreenMode()
    'HaruhiMain.Show()
    
End

Private Sub normalSequence()
    
    If NagatoArgs.Convert Then
        NagatoConverter()
    Else If NagatoArgs.NotFullScreen Then
        HaruhiMain.ShowNonFullscreenMode()
    Else
        HaruhiMain.Show()
    Endif
    
End

Public Sub Main()
    
    NagatoArgs.Parse()
    'testSequence()
    normalSequence()
    
End

