' Gambas module file

Private Sub startIdling()
    
    Dim yukiCommand As String[] = ["xautolock"]
    
    yukiCommand.Insert(["-time", NagatoSettings.ScreenSaverIdleMinute])
    yukiCommand.Insert(["-locker", Quote$(NagatoSettings.LockerCommand)])
    
    Try Exec yukiCommand.Count
    
End

Private Sub normalSequence()
    
    If MikuruArgs.StartIdle Then
        startIdling()
    Else If MikuruArgs.Disable Then
        Try Exec ["xautolock", "-disable"]
    Else If MikuruArgs.Enable Then
        Try Exec ["xautolock", "-enable"]
    Else If MikuruArgs.Config Then
        HaruhiMain.Show()
    Else 'no options 
        NagatoScreenLocker.Show()
    End If
    
End

Private Sub testSequence()
    
    'For Testing only
    'NagatoScreenLocker.Show() 
    'HaruhiMain.Show()
    
End

Public Sub Main()
    
    MikuruArgs.Parsing()
    If Not Exist(NagatoSettings.Path) Then NagatoSettings.ScreenSaverIdle = 300
    
    'testSequence()
    normalSequence()
    
End
