' Gambas module file

Public Sub Main()
    
    MikuruArgs.Parsing()
    
    'For Testing only
    'NagatoScreenLocker.Show() 
    
    If MikuruArgs.StartIdle Then
        With NagatoSettings
            Try Exec ["xautolock", "-time", .ScreenSaverIdleMinute, "-locker", Quote$(.LockerCommand)]
        End With
    Else If MikuruArgs.Disable Then
        Try Exec ["xautolock", "-disable"]
    Else If MikuruArgs.Enable Then
        Try Exec ["xautolock", "-enable"]
    Else If MikuruArgs.Config Then
        HaruhiMain.Show()
    Else 'no options 
        NagatoScreenLocker.Show()
    End If
    
End
