' Gambas module file

Property Read HostName As String

Private Sub ensure(argPath As String)
    
    Dim yukiParentDirectory As String = File.Dir(argPath)
    
    If Not Exist(yukiParentDirectory) Then ensure(yukiParentDirectory)
    If Not Exist(argPath) Then Mkdir argPath
    
End

Public Sub EnsureHostDirectory()
    
    ensure(Me.HostName)
    
End

Private Function HostName_Read() As String

    Return Desktop.DataDir &/ "NagatoBox/database"

End
