' Gambas module file

Private Const Type As String = "_NET_WM_WINDOW_TYPE"
Private Const TypeDesktop As String = "_NET_WM_WINDOW_TYPE_DESKTOP"
Private Const TypeDock As String = "_NET_WM_WINDOW_TYPE_DOCK"
Private Const TypeStrut As String = "_NET_WM_STRUT"

Public Function SetAsRoot(argWindowId As Integer) As Boolean
    
    Try Shell Subst("xprop -id &1 -f &2 32a -set &2 &3", argWindowId, Type, TypeDesktop) Wait
    
    If Error Then Return False
    
    Return True
    
End

Public Function SetAsDock(argWindowId As Integer) As Boolean
    
    Try Shell Subst("xprop -id &1 -f &2 32a -set &2 &3", argWindowId, Type, TypeDock) Wait
    
    If Error Then Return False
    
    Return True
    
End

Public Sub ReservePanelHeightOnScreen(argWindowId As Integer, argHeight As Integer) 
    
    Dim yukiValue As String = Subst$("0,0,0,&1", argHeight) 
    
    Shell Subst("xprop -id &1 -f &2 32c -set &2 &3", argWindowId, TypeStrut, yukiValue) Wait
    
End
