' Gambas module file

Public Enum None, Play, Pause, Shuffle, Repeats

Public Function CheckState(argIndex As Integer) As Boolean
    
    Select Case argIndex
        Case Me.Play
            Return NagatoQueue.State = Media.Playing
        Case Me.Pause
            Return NagatoQueue.State = Media.Paused
        Case Me.Shuffle
            Return NagatoSettingsMusic.Shuffle
        Case Me.Repeats
            Return NagatoSettingsMusic.Repeat
        Case Me.None
            Return False
    End Select
    
End

