' Gambas module file

Public Sub NewTitle(argFullPath As String, argNewTitle As String)
    
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    Dim yukiCommand As String = Subst$("id3tag -2 --song &1 &2", Quote$(argNewTitle), Quote$(yukiPath))
    
    Shell yukiCommand Wait
    
End

Public Sub NewArtist(argFullPath As String, argNewArtist As String)
    
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    Dim yukiCommand As String = Subst$("id3tag -2 --artist &1 &2", Quote$(argNewArtist), Quote$(yukiPath))
    
    Shell yukiCommand Wait
    
End

Public Sub NewAlbum(argFullPath As String, argNewAlbum As String)
    
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    Dim yukiCommand As String = Subst$("id3tag -2 --album &1 &2", Quote$(argNewAlbum), Quote$(yukiPath))
    
    Shell yukiCommand Wait
    
End

Public Sub Set(argFullPath As String, argNewTitle As String, argNewArtist As String, argNewAlbum As String)
    
    Dim yukiCommand As String = "id3tag -2 "
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    
    If argNewTitle Then yukiCommand &= Subst$("--song &1 ", Quote$(argNewTitle))
    If argNewArtist Then yukiCommand &= Subst$("--artist &1 ", Quote$(argNewArtist))
    If argNewAlbum Then yukiCommand &= Subst$("--album &1 ", Quote$(argNewAlbum))
    yukiCommand &= Quote$(yukiPath)
    
    Shell yukiCommand Wait
    
End

