' Gambas module file

Private Const TitleHeader As String = "=== TIT2 (Title/songname/content description): "
Private Const ArtistHeader As String = "=== TPE1 (Lead performer(s)/Soloist(s)): "
Private Const AlbumHeader As String = "=== TALB (Album/Movie/Show title): "
Private Const BitrateHeader As String = "Bitrate: "

Private Function getLines(argFullPath As String) As String[]
    
    Dim yukiOutput As String
    
    Shell Subst$("id3info &1", Quote$(argFullPath)) To yukiOutput
    
    Return Split(yukiOutput, "\n", "", True)
    
End

Public Sub _call(argFullPath As String) As NagatoId3TagInfo
    
    Dim yukiId3TagInfo As New NagatoId3TagInfo
    Dim yukiLine As String
    
    If Not Exist(argFullPath) Then Return yukiId3TagInfo
    
    For Each yukiLine In getLines(argFullPath)
        If yukiLine Begins TitleHeader Then yukiId3TagInfo.Title = Replace$(yukiLine, TitleHeader, "")
        If yukiLine Begins ArtistHeader Then yukiId3TagInfo.Artist = Replace$(yukiLine, ArtistHeader, "")
        If yukiLine Begins AlbumHeader Then yukiId3TagInfo.Album = Replace$(yukiLine, AlbumHeader, "")
    Next
    
    If Not yukiId3TagInfo.Title Then yukiId3TagInfo.Title = File.BaseName(argFullPath)
    
    Return yukiId3TagInfo
    
End
