' Gambas module file

Public Sub _call(argFullPath As String, argSize As Integer) As Picture
    
    Dim yukiBaseImage As New Image(argSize, argSize, Color.Transparent)
    Dim yukiImage As Image = Image.Load(argFullPath)
    Dim yukiRate As Float = Max(argSize / yukiImage.H, argSize / yukiImage.W)
    
    yukiImage = yukiImage.Stretch(yukiImage.W * yukiRate, yukiImage.H * yukiRate)
    
    Paint.Begin(yukiBaseImage)
        Paint.DrawImage(yukiImage, (argSize - yukiImage.W) / 2, (argSize - yukiImage.H) / 2)
    Paint.End()
    
    Return yukiBaseImage.Picture
    
Catch
    Return Null
    
End
