' Gambas module file

Public Sub NewTitle(argFullPath As String, argNewTitle As String)
    
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    Dim yukiCommand As String = Subst$("id3tag -2 --song &1 &2", Quote$(argNewTitle), Quote$(yukiPath))
    
    Shell yukiCommand Wait
    
End

Public Sub NewArtist(argFullPath As String, argNewArtist As String)
    
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    Dim yukiCommand As String = Subst$("id3tag -2 --artist &1 &2", Quote$(argNewArtist), Quote$(yukiPath))
    
    Shell yukiCommand Wait
    
End

Public Sub NewAlbum(argFullPath As String, argNewAlbum As String)
    
    Dim yukiPath As String = Replace$(URL.Decode(argFullPath), "file://", "")
    Dim yukiCommand As String = Subst$("id3tag -2 --album &1 &2", Quote$(argNewAlbum), Quote$(yukiPath))
    
    Shell yukiCommand Wait
    
End
