' Gambas module file

Public Function Get(argPath As String) As String
    
    Dim yukiCount As Integer
    Dim yukiReturn As String
    
    If Not Exist(argPath) Then Return argPath
    
    Do
        Inc yukiCount
        yukiReturn = Subst$("&1/&2(&3).&4", File.Dir(argPath), File.BaseName(argPath), yukiCount, File.Ext(argPath))
        If Not Exist(yukiReturn) Then Return yukiReturn
    Loop
    
End

