' Gambas module file

Property Read CharactorCode As String
Property Read ReturnCode As String

Private $charactorCode As String
Private $returnCode As String

Private Function removeCharactors(argSource As String, argToRemove As String[]) As String
    
    Dim yukiResult As String = argSource
    Dim yukiToRemove As String
    
    For Each yukiToRemove In argToRemove
        yukiResult = Replace$(yukiResult, yukiToRemove, "")
    Next
    
    Return yukiResult
    
End

Public Sub Check(argPath As String)
    
    Dim yukiOutput As String
    Dim yukiData As String[]
    
    $charactorCode = ""
    $returnCode = ""
    
    Exec ["nkf", "--guess", argPath] To yukiOutput
    
    yukiData = Split(removeCharactors(yukiOutput, ["\n", "(", ")"]), " ", "", True)
    
    If yukiData.Count = 0 Then Return
    
    $charactorCode = Replace$(yukiData[0], "_", "-")
    $returnCode = yukiData[1]
    
End

Private Function CharactorCode_Read() As String

    Return $charactorCode

End

Private Function ReturnCode_Read() As String

    Return $returnCode

End
