' Gambas module file

Private Function isClosable(argTabStrip As TabStrip, argIndex As Integer) As Boolean
    
    If argIndex = 0 Then Return False
    If 2 >= argTabStrip.Count Then Return False
    
    Return True
    
End

Private Sub deleteChildWidgets(argTabStrip As TabStrip, argIndex As Integer)
    
    Dim yukiCount As Integer

    For yukiCount = argTabStrip[argIndex].Children.Count - 1 DownTo 0
        argTabStrip[argIndex].Children[yukiCount].Delete()
    Next

End

Public Sub Delete(argTabStrip As TabStrip, argIndex As Integer)
    
    If Not isClosable(argTabStrip, argIndex) Then Return

    deleteChildWidgets(argTabStrip, argIndex)
    argTabStrip[argIndex].Delete()
    
End

Public Function GetTextArea(argTabStrip As TabStrip) As TextArea
    
    Dim yukiVBox As VBox = argTabStrip[argTabStrip.Index].Children[0]
    
    Debug yukiVBox.Count
    
    Return yukiVBox.Children[1]
    
End
